### ISSUE TITLE
Improve CLI Help Menu readability via colors and grouping of commands

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#1003]
I haven't used Rustic since v4.4 and I just updated to the most recent version. At some point, it seems that the cli menus changed format.

It used to look like this
![image](https://github.com/rustic-rs/rustic/assets/88559987/a1775a18-c35e-4459-9d61-5f5e34c9a8be)

Now it looks like this:

![image](https://github.com/rustic-rs/rustic/assets/88559987/3bee8b7b-fee9-43fa-915e-df00b3202adf)

Is there any way to bring back the colours? I find them to be much easier to visually parse

**Comment by aawsome** [comment]
We changed clap to v4 which should bring improvements in build time and binary size - besides the fact that v3 will stop getting fixes and improvments.

I don't know if there are possibilities to customize color behavior in clap, but I actually don't want to have `rustic` per default using non-default clap coloring. I also would vote against making `rustic --help` customizable.

Note there is `--help` and `-h` which give different outputs; maybe the `-h` version is more pleasant to you.

**Comment by aawsome** [comment]
Thanks for mentioning `ColorChoice`. As I understood it, this is already `Auto` (which is the default) - but only affects error messages like this:
![grafik](https://github.com/rustic-rs/rustic/assets/37850842/39b43289-edad-4d52-bfff-6a54c55e5727)

**Comment by aawsome** [comment]
Ah, the comment describes how to do it. Seems to be a pretty recent change in clap. I'll have a look at it.

**Comment by aawsome** [comment]
What about this: 
![grafik](https://github.com/rustic-rs/rustic/assets/37850842/e2ba5a5a-c6e7-4c76-abb6-9b45908fe4b5)
Or do you have better suggestions for the colors?
