### ISSUE TITLE
How to pass cli options to rclone when using rustic

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#1004]
Backblaze charges you $4/million "list" requests, and [strongly recommends](https://www.backblaze.com/docs/cloud-storage-integrate-rclone-with-backblaze-b2#fast-list-option) that you use rclone's `--fast-list` option

Is there a way to pass this through to rclone via rustic's CLI options? Or would the only way be to set environment variables? I'm trying to avoid that as it seems to complicate setting things up programmatically. 

Thanks!

**Comment by aawsome** [comment]
using 
```
[global.env]
RCLONE_FAST_LIST = "true"
```
in your config file should do the trick.

Besides this, I doubt that it will make a significant difference in your backblaze charges. IMO this only affects `check` and `prune` (and `forget --prune`, of course) and may reduce number of list calls by 255 per command call, i.e. saving you $0.001 per `check` or `prune` call.
`backup` will not be affected at all by this option.
