### ISSUE TITLE
CouldNotGetElapsedTimeFromSystemTime should be ignored

### ISSUE THREAD

**Issue by 20051231** [rustic-rs/rustic#1018]
When running a long backup operation, rustic crashed with the following error.

```
 error: couldn't get elapsed time from system time: `SystemTimeError(1.1449058s)`
```

After checking the code, the error may be come from these two places where `elapsed` throws a error.

https://github.com/rustic-rs/rustic_core/blob/0872923397b384a7b39ee092ae660f9d144c67f1/crates/core/src/blob/packer.rs#L521
https://github.com/rustic-rs/rustic_core/blob/0872923397b384a7b39ee092ae660f9d144c67f1/crates/core/src/index/indexer.rs#L187

According to 
https://doc.rust-lang.org/std/time/struct.SystemTimeError.html

this error just means the offset is negative and the code is just checking the timeout for writing the pack.
I suspect there is some NTP time sync operation running in between the creation of pack file and the checking function which turn back the system time such that the offset becomes negative. 

I think `unwrap_or_default` is enough in this case since the error is not fatal.

**Comment by aawsome** [comment]
Thanks a lot for reporting @20051231! You are right - aborting is a wrong handling of this case. I'll make a PR which prints a warning but continues with the backup.

**Comment by aawsome** [comment]
Also thanks a lot for your good analysis of the error! If you find more errors, you are also welcome to directly create a PR - this ensures that things are fixed even more quickly!

**Comment by aawsome** [comment]
sorry - closed by accident
