### ISSUE TITLE
B2 backend support

### ISSUE THREAD

**Issue by HaleTom** [rustic-rs/rustic#1028]
Are there plans for supporting B2?

```
% rustic backup --repository b2:restic-hale
using no config file, none of these exist: /home/ravi/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
error: backend "b2" is not supported!
```

**Comment by HaleTom** [comment]
It seems like work is (slowly) underway:

https://github.com/rustic-rs/rustic/discussions/900#discussioncomment-7115951

**Comment by aawsome** [comment]
There ist b2 support via rclone in 0.6.1. And we've added the possibility to use many more backends natively via opendal in the current development version which is about to be released soon.

Try to use the latest [nightly build](https://github.com/rustic-rs/nightly) - There s3 is supported which should also work with b2.
There is also direct b2 support in opendal but IMO its a not as mature as the s3 - and rustic so far only supports the syntax "s3:", "sftp:" (on unix only) and "opendal:<Service>" where all other options have to be given in the config file.

Happy to get feedback on the new backends! And if you have questions, please don't hesitate to ask!

**Comment by HaleTom** [comment]
Thanks!

I'll wait for this to appear in a release as I'm conservative with backups.

**Comment by aawsome** [comment]
B2 now works directly with rustic 0.7.0, see https://github.com/rustic-rs/rustic/blob/main/config/services/b2.toml

**Comment by HaleTom** [comment]
Excellent - I'm trying it now.  Thanks!!! :)
