### ISSUE TITLE
`repository = "s3:..."` doesn't work as expected

### ISSUE THREAD

**Issue by simonsan** [rustic-rs/rustic#1045]
TL;DR: use `repository = "opendal:s3"` like specifed in https://github.com/rustic-rs/rustic/tree/main/config/services

As this works:

```
[repository]
repository = "opendal:s3"
password = "pass"

[repository.options]
root = "/"
bucket = "test-dal"
endpoint = "https://p7v1.ldn.idrivee2-40.com"
region = "gb-ldn"
access_key_id = "xxx"
secret_access_key = "xxx"
```

and this does not:

```
[repository]
repository = "s3:https://p7v1.ldn.idrivee2-40.com/test-dal"
password = "pass"

[repository.options]
access_key_id = "xxx"
secret_access_key = "xxx"
region = "gb-ldn"
```

It looks like s3 backend has some problem collecting all data from toml file. Both examples above contain all the same information.

_Originally posted by @kapitainsky in https://github.com/rustic-rs/rustic/discussions/1044#discussioncomment-8361543_

**Comment by simonsan** [comment]
It looks like rustic internally sets `endpoint=http://127.0.0.1:9000/` (with a trailing slash). This causes a request url like this `http://127.0.0.1:9000//rustic/config`.  
If I set `endpoint` to that value manually I get the same error.
It seems like Minio does not like the `//`.

_Originally posted by @l-austenfeld in https://github.com/rustic-rs/rustic/discussions/1044#discussioncomment-8361547_

**Comment by aawsome** [comment]
We'll remove the possibility to use `"s3:.."` in the next release. `opendal` is the preferred way and works for all users.
