### ISSUE TITLE
Example b2.toml issues

### ISSUE THREAD

**Issue by HaleTom** [rustic-rs/rustic#1068]
https://github.com/rustic-rs/rustic/blob/main/config/services/b2.toml

What's the difference between `application_key` and `application_key_id`?

Both are required:

    error: backend openDAL Backend cannot be loaded: ConfigInvalid (permanent) at Builder::build, context: { service: b2 } => application_key_id is empty

    error: backend openDAL Backend cannot be loaded: ConfigInvalid (permanent) at Builder::build, context: { service: b2 } => application_key is empty

However, `application_key_id` is not provided in the example.

`".my_key"` is given as an example value for the `application_key` field.  Is the intent that the value of this key is a filename?  

If so, what is the directory name that `.my_key` is relative to?

**Comment by aawsome** [comment]
The opendal docu https://opendal.apache.org/docs/rust/opendal/services/struct.B2.html is a bit irritating here.

I think it should be 
```
root = "repo-path" # Set the work directory for backend
application_key_id = "my_id" # B2 application key keyID
application_key = "my_key" # B2 application key applicationKey
bucket = "bucket_name" # B2 bucket name
bucket_id = "bucket_id" # B2 bucket_id
```
All are just strings, no filenames. Please report once you have a working config, we'll change the b2.toml then.

**Comment by aawsome** [comment]
Actually I tested b2 myself successfully (using `application_key_id`), but I think  I copy&pasted from the the opendal docu instead of from my working config.

**Comment by HaleTom** [comment]
The required fields are:

```
# These are required either here or set by config variables
# https://github.com/apache/opendal/blob/main/.env.example
#
# application_key_id = "" # B2 application key keyID
# application_key = "" # B2 application key applicationKey
# bucket_id = "" # B2 bucket_id
# bucket = "" # B2 bucket name
```

So, basically: `s/key_id/application_key_id/`.

I'd recommend that you put the URL and commend in the config file to help people with security.

**Comment by HaleTom** [comment]
I created a PR:
https://github.com/rustic-rs/rustic/pull/1072
