### ISSUE TITLE
Backup path without parent directories

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#107]
If I backup, say, `/root/rustictest1/rustictest2` to `rclone:onedrive:rustic`, it seems to create `/root` and `/root/rustictest1` directories. And if I was only backing up a deeply nested directory, it would create a chain of empty parent folders.

Is there any way for it to just create `rclone:onedrive:rustic/rustictest2`, without the `root` and `rustictest1` parent folders?

Is this even desirable?

**Comment by aawsome** [comment]
Right, this is the behavior, I've chosen.

Do you encounter any problem with this behavior? When you access the generated snapshot, you can use a subpath within the snapshot with most command.

For instance, when you want to restore the created snapshot crated by backing up `/root/rustictest1/rustictest2`, you can use
```
rustic-rs -r rclone:onedrive:rustic restore <SNAPID>:/root/rustictest1 /dest-dir
```
and it will not create `/root` and `/root/rustictest1` in `/dest-dir`.
