### ISSUE TITLE
Set OpenDAL secrects via environment variables

### ISSUE THREAD

**Issue by HaleTom** [rustic-rs/rustic#1073]
There are several B2 variables listed in this [OpenDAL `.env` example](https://github.com/apache/opendal/blob/39e0a69c8eadc44391ba0420fdc7de2a42962ecf/.env.example#L173-L178):
```
OPENDAL_B2_ROOT=/path/to/dir
OPENDAL_B2_BUCKET=<bucket>
OPENDAL_B2_BUCKET_ID=<bucket_id>
OPENDAL_B2_APPLICATION_KEY_ID=<key_id>
OPENDAL_B2_APPLICATION_KEY=<application_key>
```

[OpenDAL asserts that they are working correctly](https://github.com/apache/opendal/issues/4199#issuecomment-1951905449).

But with these set, I get:

    08:23:27 [DEBUG] (1) opendal::services::b2::backend: backend build started: B2Builder { config: B2Config { root: Some("/"), application_key_id: None, bucket_id: "", bucket: "", .. }, .. }

Do these need to be accessed and/or passed on to OpenDAL?

----

### Prior art:
opendal: Do OPENDAL_B2_* environment variables work? #4199
https://github.com/apache/opendal/issues/4199

**Comment by Xuanwo** [comment]
Hi, the `OPENDAL_` prefix is used internally within the opendal project and isn't part of its public API. This means applications like `rustic` cannot initialize storage using this method unless they decided to implement the same env loading logic.

**Comment by HaleTom** [comment]
To not force secrets being stored in config files, it would be great to support reading secrets from environment variables, (like is available in restic).
