### ISSUE TITLE
Add detail to the documention about --instant-delete

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#108]
From your commentary in https://github.com/rustic-rs/rustic/pull/70

You have to use forget --prune --instant-delete. Without --prune, forget does not prune anything, only removes snapshot files.

Instant-delete does exactly what restic is doing except creating locks.
So the question is mainly, what rustic is doing when you don't specify instant-delete: It uses a two-phase deletion, i.e. packs-to-remove are not immediately removed but first marked for some time, see https://github.com/rustic-rs/rustic/blob/main/FAQ.md

This two-phase deletion is needed for rustic to work lock-free: If a backup runs parallel to a prune run (or forget --prune), it could be that prune decides that some blobs can be removed, but the parallel backup uses these blobs for the newly generated snapshot.

The time to hold marked packs should be long enough to guarantee that a possibly parallel backup run has finished in between. It can be set by the --keep-delete option and defaults to 23 hours. In any case, packs will be kept marked and only deleted by the next prune run.

The --instant-delete now circumvents this protection and instantly removes the packs-to-delete instead of marking them. So it is only advised if you KNOW that no parallel access to your repo is made.

**Comment by aawsome** [comment]
Create minds think alike :wink:
Just made #109 in time...
