### ISSUE TITLE
Render TOML version of `show-config`

### ISSUE THREAD

**Issue by AlphaJack** [rustic-rs/rustic#1093]
Hi, would it be possible to get the output of `show-config` in JSON format? Right now the `--json` flag is not supported

**Comment by aawsome** [comment]
Actually I think it would be better to output some TOML - as the file format is toml, too. And I think it would be better to rename as it is a bit ambiguous (there is the profle config we are talking here and the in-repo config which can be set by `rustic config`). Maybe something like `show-profile`? or `profile show-config`?

**Comment by simonsan** [comment]
I agree with the `toml` choice, also because you can output it via `>>` to another file from that to copy a config. With the renaming, I would wait until we think about the cli refactor (if we want to go down this route)?

**Comment by aawsome** [comment]
Is implemented via #1095. I close this issue - the renaming of commands is another concern.
