### ISSUE TITLE
Failures due to missingg credentials generate incorrect exit code

### ISSUE THREAD

**Issue by mprasil** [rustic-rs/rustic#1096]
I've ran rustic without password by mistake and it failed:

```sh
# rustic backup /some/path
[INFO] using config /etc/rustic/rustic.toml
error: No password given. Please use one of the --password-* options.
```

However exit code was `0`:

```sh
# echo $?
0
```

Same for missing repository credentials without anonymous access. I don't think this is correct behavior as it could lead to backup scripts failing silently.

**Comment by simonsan** [comment]
This is a duplicate, please make sure to search the issues before opening a new one, or start a new [discussion](https://github.com/rustic-rs/rustic/discussions).

CC: https://github.com/rustic-rs/rustic/issues/927
