### ISSUE TITLE
rustic[2825274]: [WARN] Could not determine rclone version: error parsing verision number from `"1.63.0-beta.7022.e649cf4d5"`

### ISSUE THREAD

**Issue by stdedos** [rustic-rs/rustic#1097]

**Comment by aawsome** [comment]
Thanks for opening this issue @stdedos!

We have this warning as rclone < 1.52.2 wasn't able to support setting user/password via env variable. This would result in a running rclone without authentication which can be a security problem depending on the circumstances you run rustic.

As your version has too many `.` inside, our current version parsing fails.

**Comment by aawsome** [comment]
Until the fix is included in rustic, you can use 
```
[repository.options]
rclone-command = "rclone serve restic --addr localhost:0"
```
which skips the version check.
