### ISSUE TITLE
Diff results are randomly(?) reversed

### ISSUE THREAD

**Issue by ravenmaw** [rustic-rs/rustic#1103]
A test with v0.7.0.

- Creating a repo with an empty password and two differing snapshots: 

`mkdir repo data`
`touch pass`
`rustic -r repo -p pass init`
`touch data/file1`
`rustic -r repo -p pass backup data`
`touch data/file2`
`rustic -r repo -p pass backup data`

- Diffing the snapshots: `rustic -r repo -p pass diff 32bf5b00 b2384661` x10, with following results:

`+    "[...]/data/file2"`
`+    "[...]/data/file2"`
`+    "[...]/data/file2"`
`-    "[...]/data/file2"`
`+    "[...]/data/file2"`
`-    "[...]/data/file2"`
`-    "[...]/data/file2"`
`-    "[...]/data/file2"`
`+    "[...]/data/file2"`
`-    "[...]/data/file2"`

Happens consistently with all my repos (local, rest, rclone). As if the order of snapshot id's were randomly swapped. Everything else seems to work normally.

**Comment by aawsome** [comment]
Thanks a lot for reporting @ravenmaw 
In fact this is a bug due to parallelization of file reading: The come in random order.
I opened a PR in rustic_core to fix it.
