### ISSUE TITLE
rustic with local backend always creates repository folder if it doesn't exist

### ISSUE THREAD

**Issue by AlphaJack** [rustic-rs/rustic#1107]
I think this is an unwanted behavior of `repoinfo`, as it prompts for a password, print this error and create an empty folder:

```
$ rustic --repo ~/Desktop/non-existent repoinfo --json
enter repository password: [hidden]
error: No repository config file found. Is there a repo at local:/home/jack/Desktop/non-existent?
```

I think the correct order should be:

1. check if folder exists, error if not (do not create an empty folder)
2. check if repo config file exists, error if not
3. prompt for password

The option `--only-files` does not error, but still creates an empty foler

**Comment by aawsome** [comment]
@AlphaJack Thanks a lot for reporting! Actually only the local backend is affected - there all commands (also read-only ones) currently do create the repo dir, if it doesn't exist.
