### ISSUE TITLE
Update help text of prune --keep-delete

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#111]
I ran `prune --keep-delete 10m` and confirmed that the files had been marked for deletion with `repoinfo`. However, I came back 10m+ later and they were still there. I then ran `prune` again and they were still not removed.

Am I making a mistake somewhere?

**Comment by aawsome** [comment]
Thanks for your question! The `--keep-delete` option is evaluated by the `prune` run which deletes marked files. In your case, it must be specified in the second, and not (necessarily) in the first run.

I would actually advise to always run `prune` with the same options as one run can at the same time mark unused packs for removal and remove previously marked packs if they are still not used and the mark is old enough.
