### ISSUE TITLE
config command invalidates config file (Error: crypto error)

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#112]
I just created a new local repo and after a few backups and prunes, i'm getting this error on any command

```
password is correct
Error: crypto error
```

I'm not sure how to get more information as `check` and other commands don't work

**Comment by aawsome** [comment]
Thanks for this issue! Would be great if you could describe the steps how to reproduce the behavior!

**Comment by aawsome** [comment]
Mhh.. I'm trying to reproduce the error, but I'm not succeeding. 
Can you give the exact sequence of commands you are using?

**Comment by aawsome** [comment]
Ok, I found it. It was actually a quite subtle bug in the local backend:
The local backend does not remove or truncate files in the backend when they are already existing. This normally is no problem as the files in the repo are unique (filename = has of content). The only exception is the config file (which is actually a misconcept in the restic repo format, IMHO) and this file is usually not much overwritten. Well, except by the rustic `config` command. So the `config` command "destroys" the config file if:
- you are using a local backend
- the new config is shorter than the present one

A work-around is to use the rclone backend to access the local repo: `rustic-rs -r rclone:/path/to/repo`.
This bug will be also corrected soon!

@nickchomey Thanks a lot for finding this very subtle bug!

**Comment by aawsome** [comment]
Please report if this also occurs with the rclone backend. I wasn't able to reproduce it using it and I'm quite sure the bug doesn't exist there...

**Comment by aawsome** [comment]
Note that there is a possibility to "repair" a config file which has been generated by this bug. If anyone invalidated a repo which is needed, please report here!
I will then describe how to proceed with the repairing.

**Comment by aawsome** [comment]
I just merged #115 which should fix this bug. 
@nickchomey Can you confirm that the latest beta doesn't contain this bug anymore?

**Comment by aawsome** [comment]
Thanks for the confirmation!
