### ISSUE TITLE
windows: not asking for password when using backup command

### ISSUE THREAD

**Issue by kkettinger** [rustic-rs/rustic#1153]
It seems that when you use the `backup` command under windows, you are not prompted for the password:
```
D:\Tmp\rustic>rustic init -r repo
[INFO] using no config file, none of these exist: C:\Users\kk\AppData\Roaming\rustic\config\rustic.toml, C:\ProgramData\rustic\config\rustic.toml, .\rustic.toml
enter password for new key: [hidden]
[INFO] key 1e2b821d successfully added.
[INFO] repository d88d1b15 successfully created.
[INFO] using cache at C:\Users\kk\AppData\Local\rustic\d88d1b1554269c71c927bc2d761c85cad1e71713bfbb3b72f9685c1c07662953

D:\Tmp\rustic>rustic -r repo backup test
[INFO] using no config file, none of these exist: C:\Users\kk\AppData\Roaming\rustic\config\rustic.toml, C:\ProgramData\rustic\config\rustic.toml, .\rustic.toml
error: No password given. Please use one of the --password-* options.
```

Looking at the [documentation](https://rustic.cli.rs/docs/commands/backup/creating_snapshots.html), you should be prompted when using the `backup` command. Also, I don't see any way to force rustic to prompt me for the password.

I'm using `rustic 0.7.0` installed with `cargo` under windows 10.

**Comment by aawsome** [comment]
Thank you for opening this issue @kkettinger!
I think this has been already fixed in https://github.com/rustic-rs/rustic/pull/1061. Can you please test the nightly build?

**Comment by kkettinger** [comment]
@aawsome It works when building it directly from main, thanks!
