### ISSUE TITLE
Feature request: nice readable backup summary print

### ISSUE THREAD

**Issue by mrlee14** [rustic-rs/rustic#1156]
personalty would appreciate summary at the and of backup, in a simple readable text format, of what was done so far, the essential details....

**Comment by aawsome** [comment]
@mrlee14 Can you please give some more details? What kind of information are you missing?

Do you know about `rustic backup --json` and `rustic snapshots --long` / `rustic snapshots --json`?

**Comment by mrlee14** [comment]
> @mrlee14 Can you please give some more details? What kind of information are you missing?
> 
> Do you know about `rustic backup --json` and `rustic snapshots --long` / `rustic snapshots --json`?

OK, I see all details and so on.., maybe the option to disable '[INFO]' lines on cli backup cmd and print only 'backing up...' lines, less verbose, its perhaps already configurable?...

**Comment by mrlee14** [comment]
> > @mrlee14 Can you please give some more details? What kind of information are you missing?
> > Do you know about `rustic backup --json` and `rustic snapshots --long` / `rustic snapshots --json`?
> 
> OK, I see all details and so on.., maybe the option to disable '[INFO]' lines on cli backup cmd and print only 'backing up...' lines, less verbose, its perhaps already configurable?...

its not truly necessary, as is is already very good...

**Comment by aawsome** [comment]
@mrlee14 I already heard other users that the output verbosity should be discussed and maybe changed. So far, you can use `--level=` to set the output verbosity, the default is `info`. Do you think we should start a discussion about better verbosity and better defaults?

About the summary output: We can easily add a `--long` option to the `backup` command which would output the summary like `snapshots` is currently doing. Would you see this as valuable?

**Comment by mrlee14** [comment]
> @mrlee14 I already heard other users that the output verbosity should be discussed and maybe changed. So far, you can use `--level=` to set the output verbosity, the default is `info`. Do you think we should start a discussion about better verbosity and better defaults?
> 
> About the summary output: We can easily add a `--long` option to the `backup` command which would output the summary like `snapshots` is currently doing. Would you see this as valuable?

Yes, I think this would be very interesting to have at the bottom of backup, nicely formatted…

**Comment by intgr** [comment]
Something that I would find extremely useful in output is a summary of what is expanding my repository size. I couldn't care less about some extra megabytes per snapshot, but if I keep accidentally adding stuff to backup that I don't want there, it may eventually get in trouble with my cloud storage quota.

So maybe:

* A summary of new directories/paths added compared to previous backup, if their size exceeds a threshold. E.g. if I have cloned a new directory `~/git/linux` which adds 6 GB to the repository, I'd like to know immediately so I can adjust my ignore rules and delete that snapshot. To be useful, this should be the size of the whole directory including all files recursively.
* Similarly, if an existing file has a large amount of changes, it would be nice to know about that. Ideally Rustic would summarize it per directory if there are changes to lots of files in a single directory, but that may require some complicated heuristics.

  * For some use cases, lots of changes is to be expected, so perhaps this should be a "top 5" or "top 10" list.
