### ISSUE TITLE
Snapshot grouping with same dirs but different order

### ISSUE THREAD

**Issue by webdjoe** [rustic-rs/rustic#1158]
I have a curious issue where my snapshots are separated into separate groups, even though they have the same host, label and path. Not sure if it is related but the files, dirs and size columns have a "?". I tried the usual `repair index`, `repair snapshots`, `check`, and `prune` but cannot seem to get them grouped. I believe these were originally created by restic. Is there any way to get these to group together? This is a minor example but I have other systems that have significant sized backups that I do not want to lose deduplication efficiency or skew retention.

I am using rustic v0.7.0-45-gfc8e3c5-nightly with minio S3 storage.

```
snapshots for (host [probox], label [home], paths [/home,/root])
| ID       | Time                | Host   | Label | Tags   | Paths | Files | Dirs |      Size |
|----------|---------------------|--------|-------|--------|-------|-------|------|-----------|
| 02f30608 | 2024-05-27 19:24:39 | probox | home  | home   | /home |  2606 |  217 | 196.6 MiB |
|          |                     |        |       | probox | /root |       |      |           |
1 snapshot(s)

snapshots for (host [probox], label [home], paths [/root,/home])
| ID       | Time                | Host   | Label | Tags     | Paths | Files | Dirs | Size |
|----------|---------------------|--------|-------|----------|-------|-------|------|------|
| f186d0eb | 2024-04-14 06:30:39 | probox | home  | home     | /root |     ? |    ? |    ? |
|          |                     |        |       | original | /home |       |      |      |
|          |                     |        |       | probox   |       |       |      |      |
| f7d394f2 | 2024-05-01 06:30:52 | probox | home  | home     | /root |     ? |    ? |    ? |
|          |                     |        |       | original | /home |       |      |      |
|          |                     |        |       | probox   |       |       |      |      |
```

Configuration:

```
[backup]
label = "home"
custom-ignorefile = []
iglob-file = ["/root/.config/rustic/globs/primary.glob", "/root/.config/rustic/globs/home.glob"]
host = "probox"
tag = ["probox", "home"]
init = true
one-file-system = true

[[backup.sources]]
source = "/home /root"

[forget]
prune = true
group-by = "host,label,paths"
keep-tags = ["keep-forever"]
keep-last = 0
keep-daily = 7
keep-weekly = 1
keep-monthly = 1
keep-quarter-yearly = 4
keep-half-yearly = 2
keep-yearly = 10
```

**Comment by aawsome** [comment]
@webdjoe Thanks for opening the issue!

About the grouping: The groups are not completely identical as the paths are swapped. But I agree that maybe that shouldn't matter for the group, so I think this should be fixed in rustic.

In your example you have nice (identical) labels for fitting groups of paths. If this is the case, you can simply just group by `host,label` to get the desired grouping.

About deduplication efficiency: Note that this is completely unrelated to grouping of snapshots. Deduplication is always achieved over all snapshots in a repository.

About the `?`: Yes, summary information is not present for all snapshots and only shown if it is added when the snapshot is created. This is expected behavior if, for instance, some snapshots are generated by (older) restic versions. There might be future versions of `rustic repair snapshots` which are able to calculate this summary information and add it to existing snapshots.

**Comment by webdjoe** [comment]
Thank you for the quick response. I was fixated on the `?` so I didn't realize the order of directories. I tried to set `group-by` to `hosts,label` in the backup and forget sections but the snapshot list is still showing in the original grouping.

I tried grouping by tags as well and that was ignored. 

Also, weirdly enough I changed the order of directories back to the original and it is throwing backups into the new grouping. The latest backup 5/28 uses the following configuration file. You can also see I used a `merge` tag on some snapshots (with interactive mode which is awesome!) to filter, which are also grouped. Am I missing something obvious here? 

```
snapshots for (host [probox], label [home], paths [/home,/root])
| ID       | Time                | Host   | Label | Tags   | Paths | Files | Dirs |      Size |
|----------|---------------------|--------|-------|--------|-------|-------|------|-----------|
| 542d84b9 | 2024-05-13 06:30:56 | probox | home  | merge  | /home |  2607 |  243 | 167.8 MiB |
|          |                     |        |       |        | /root |       |      |           |
| 47c341ff | 2024-05-22 06:30:49 | probox | home  | merge  | /home |  2620 |  248 | 168.4 MiB |
|          |                     |        |       |        | /root |       |      |           |
| bfa2edde | 2024-05-28 02:19:01 | probox | home  | home   | /home |  2624 |  220 | 217.5 MiB |
|          |                     |        |       | probox | /root |       |      |           |

12 snapshot(s)

snapshots for (host [probox], label [home], paths [/root,/home])
| ID       | Time                | Host   | Label | Tags   | Paths | Files | Dirs | Size |
|----------|---------------------|--------|-------|--------|-------|-------|------|------|
| e9c46f71 | 2024-05-23 06:30:50 | probox | home  | home   | /root |     ? |    ? |    ? |
|          |                     |        |       | probox | /home |       |      |      |
| 17abba1a | 2024-05-24 06:31:01 | probox | home  | home   | /root |     ? |    ? |    ? |
|          |                     |        |       | probox | /home |       |      |      |
| f5b05826 | 2024-05-25 06:30:55 | probox | home  | home   | /root |     ? |    ? |    ? |
|          |                     |        |       | probox | /home |       |      |      |
| d458e618 | 2024-05-26 06:30:58 | probox | home  | home   | /root |     ? |    ? |    ? |
|          |                     |        |       | probox | /home |       |      |      |
| 3a955de4 | 2024-05-27 06:30:41 | probox | home  | home   | /root |     ? |    ? |    ? |
|          |                     |        |       | probox | /home |       |      |      |
```

Configuration:

```
[backup]
label= "home"
custom-ignorefile = []
iglob-file = ["/root/.config/rustic/globs/primary.glob", "/root/.config/rustic/globs/home.glob"]
host = "probox"
tag = ["probox", "home"]
init = true
one-file-system = true
group-by = "host,label,tags"

[[backup.sources]]
source = ["/root", "/home"]

[forget]
prune = true
group-by = "host,label,tags" # Can be any combination of host,label,paths,tags
# The following filter options can be also defined here and then overwrite the options for the forget command
# The retention options follow. All of these are not set by default.
keep-tags = ["keep-forever"]
keep-last = 0
keep-daily = 7
keep-weekly = 1
keep-monthly = 1
keep-quarter-yearly = 4
keep-half-yearly = 2
keep-yearly = 10
```

I made a script that I would solve the problem of moving the old snapshots with the original order into the new grouping. It basically does a single merge command for each snapshot (also calculates size, file & dir count). However, after switching the order of directories in the configuration file, it is still placing snapshots into the new directory order grouping (even with group-by = "host,label")

```sh
#!/bin/bash

tag_filter="merge"
tags="probox,home"
label="home"

# Get snapshot ID's into array - requires jq
ids=($(rustic -P home_bb snapshots --filter-tags "$tag_filter" --json | jq '[..|.id?|select(.!=null)]' | tr -d '[],"'))

# loop through snapshot ID's and do a single merge with label and tags
for snapshot in "${ids[@]}"; do
  rustic -P home_bb merge "${snapshot:0:8}" --delete --tag "$tags" --label "$label"
done
```

**Comment by aawsome** [comment]
@webdjoe I think there are two points to mention:
- for the `snapshots` command, there is no possibility to specify `--group-by` in the config profile, i.e. you have to specify it as CLI parameter
- when `rustic` creates a new snapshot, it always sorts paths (and tags) before saving it. A changed order will therefore have no effects.

**Comment by aawsome** [comment]
@webdjoe I made a PR to rustic_core which fixes the grouping of non-ordered paths/tags. Once this is merged and used in rustic, you should be able to use your "old" and "new" snapshots together.

**Comment by webdjoe** [comment]
Wow that's great, thank you for the quick turnaround. 

That makes sense with the sorted paths. Out of curiosity, what does the `group-by` items in the backup section do? The forget section most likely works with retention, but how does it impact backups?

**Comment by aawsome** [comment]
> Out of curiosity, what does the `group-by` items in the backup section do? The forget section most likely works with retention, but how does it impact backups?

For `backup` , the `-group-by` option only impacts the parent snapshot that is taken to speed-up the backup: Here, the last snapshot of the same group as the snapshot-to-create is used.
