### ISSUE TITLE
WebDAV configuration isn't working in windows

### ISSUE THREAD

**Issue by douglasparker** [rustic-rs/rustic#1163]
Tested with `latest` and `rustic v0.7.0-45-gfc8e3c5-nightly`

`rustic webdav` binds to `http://[::1]:8000` despite the configuration.

```
[webdav]
address = "127.0.0.1:8000"
path-template = "[{hostname}]/[{label}]/{time}" # The path template to use for snapshots. {id}, {id_long}, {time}, {username}, {hostname}, {label}, {tags}, {backup_start}, {backup_end} are replaced. [default: "[{hostname}]/[{label}]/{time}"]. Only relevant if no snapshot-path is given.
time-template = "%Y-%m-%d_%H-%M-%S"
symlinks = false
file-access = "read"
```

**Comment by nardoor** [comment]
Hello,

To me, the address `[::1]` is the IPv6 equivalent of `localhost` (same as `127.0.0.1` for IPv4).

Are you certain that you can't connect to the **webdav** using `127.0.0.1:8000` when rustic says that it binds on `http://[::1]:8000`? 
I'm assuming it should work, let me know if I am being wrong.

**Comment by douglasparker** [comment]
@nardoor Yep, I'm certain. Feel free to test it out yourself.

**Comment by KamikazeePL** [comment]
On Windows 10 home it sometimes can not connect from Explorer but WinSCP I can connect and browse and copy files.

**Comment by nardoor** [comment]
> @nardoor Yep, I'm certain. Feel free to test it out yourself.

This indeed was a bug, thanks for reporting. I apologize for taking so long to fix it.

`rustic` totally ignored the toml config. 
 #1241 fixes it
