### ISSUE TITLE
Running commands given in the documentation are throwing errors

### ISSUE THREAD

**Issue by ykiran** [rustic-rs/rustic#1182]
I was trying out rustic today and while creating a snapshot using the command example in the documentation, I got the following error:

rustic -r F:\MyBackups --verbose backup E:\folder\
error: unexpected argument '--verbose' found

  tip: a similar argument exists: '--version'

Usage: rustic --version <--repository <REPOSITORY>|--repo-hot <REPO_HOT>> <COMMAND>

For more information, try '--help'.

=========================================================
I was able to create a snapshot after running the command without the 'verbose' option.

Later, when I tried the command to list snapshots, I got another error:

rustic -r F:\MyBackups snapshots
error: rustic-rs fatal error: parse error: invalid escape character in string: `R` at line 2 column 18

Please help.
Is there another update/fix I'm unaware of?

**Comment by aawsome** [comment]
docu has been updated: Use `--log-level` instead of `--verbose`.
