### ISSUE TITLE
`rustic forget` delete all snapshot without any warning

### ISSUE THREAD

**Issue by 9-2-1** [rustic-rs/rustic#1191]
`rustic forget` will delete all snapshot without any warning. Snapshots may lost accidently because of missing snapshot IDs.

Suggestion:

Reject if all snapshot will be deleted by `rustic forget` or use `rustic forget --all` to confirm.

**Comment by aawsome** [comment]
Thanks for opening this issue @9-2-1 !

I actually don't know if the ability to remove all snapshots is a bug or a feature - given that restic does have this behavior and there are people trying to force all snapshots to be removed...

Another thought: The unix `rm` command is also able to remove all files without extra verification.

And the`forget` command even does have a `--dry-run` option. Plus, if you specify a suitable retain option, e.g. in a configuration profile, it will ensure that snapshots satisfying that policy will be kept. Moreover, there is the ability to add snapshot-dependant delete protection.

Can you describe your use-case more in detail?

**Comment by 9-2-1** [comment]
> given that restic does have this behavior and there are people trying to force all snapshots to be removed...

Running `rm` without any argument will fail immediately with an error message.

Running `restic forget` without extra arguments will fail too.

But running `rustic forget` without extra arguments will delete all snapshot, which is really risky.

Suggestion: `rustic forget` should fail without extra arguments just like what rm and restic do.

For people who want to delete all snapshots, they can run something explicitly like `rustic forget --all`.

**Comment by aawsome** [comment]
Ok, I see only voices voting pro an additional protection...
Am I getting this right that this should be a protection about users unwillingly not specifying any `keep-*` option and therefore removing all snapshots accidentally?

In https://github.com/rustic-rs/rustic_core/pull/238 I proposed a change which checks if there is no `keep-*` option given. Also a new `keep-none` option is added which allows to remove all snapshots (if given as single `keep-` option). What do you thing about the name? Is this a good name?
