### ISSUE TITLE
using global results in random files being ignored

### ISSUE THREAD

**Issue by lostb1t** [rustic-rs/rustic#1199]
When using glob some files are ignored that are not in the glob pattern

for example:

`2024-08-12T09:24:23.769274359Z [DEBUG] (35) ignore::walk: ignoring /data/stalwart_test/etc/config.toml`

```
[repository]
repository = "opendal:s3"

[repository.options]
bucket = "backups"
endpoint = "xxx"
access_key_id = "xxx"
secret_access_key = "xxx"
region = "auto"

[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]
custom-ignorefile = [".rusticignore", ".backupignore"]
glob = ["**/*[!.log]"]

[[backup.sources]]
source = "/data"
host = "leia"

[forget]
prune = false
filter-host = ["leia"]
keep-last = 20
keep-weekly = 1
keep-monthly = 1
keep-yearly = 1

```

**Comment by aawsome** [comment]
@lostb1t Did you find something which explains this? Or did you accidentally close it? I reopen as so far this seems to be unclear what reason is..

**Comment by aawsome** [comment]
Only think which would be interesting is: Are there `.rusticignore` or `.backupignore` files somwhere under `data` and what do they contain, if there are?

**Comment by lostb1t** [comment]
closed it because i retested my glob pattern with another tool. And sure enough it skipped some files. So i rewrote the glob and all is fine.

PEBCAK

**Comment by aawsome** [comment]
Ok, thanks for the feedback, this help other we may stumble over this issue in future!

I agree that we close this as resolved.
