### ISSUE TITLE
Lock file out of sync

### ISSUE THREAD

**Issue by alerque** [rustic-rs/rustic#1204]
The v0.8.0 version bump got set in the manifest, but the lock file is out of sync. This means the app will not build in `--locked` mode. I'm trying to bump the Arch Linux package, but this is causing the build to fail. We could fudge and generate our own, but then we wouldn't be using anything consistent across distros and our own package wouldn't be reproducible.

Can you please consider updating the lock file and putting out a patch release? In the future make sure you bump both the lock file and manifest together when changing the release version. Thanks.

**Comment by aawsome** [comment]
Thanks @alerque for opening this issue!

In fact we are trying to automate the releasing more and more. While trying to use more automation I did not run a cargo build locally anymore to see if it makes changes in the lock file... I think we'll add a locked build to the release pipeline to check for this kind of problem in future...

Anyway, yes, we can do a patch release. I would like to wait for a couple of days if other problems show up and then do another release.
