### ISSUE TITLE
Add more filter options

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#1213]
I think having more filter options would be very nice.

Some ideas (names need to be discussed)
- filter-before or filter-older-than to filter out too old snapshots
- filter after or filter-newer-than to filter out too young snapshots
- filter-size-greater-than
- filter-size-lower-than
- filter-tags-exactly to allow to specify one or more exact taglists to filter in contrast to `filter-tags` which does filter by any tag which is given in one of the provided taglists

**Comment by simonsan** [comment]
Fixed by #1263
