### ISSUE TITLE
Can we avoid creating empty folders when initializing a repo?

### ISSUE THREAD

**Issue by AlphaJack** [rustic-rs/rustic#1315]
Is it needed to create all 256 data/ folders when initializing a repo? Or could they also be created when needed?

Borg:

```
└── 0
    ├── 0
    ├── 1
    ├── 10
    ├── 11
    ├── 12
    ├── 13
    ├── 14
    ├── 15
    ├── 16
    ├── 17
    ├── 18
    ├── 19
    ├── 2
    ├── 20
    ├── 21
    ├── 3
    ├── 4
    ├── 5
    ├── 6
    ├── 7
    ├── 8
    └── 9

2 directories, 22 files
```

Rustic:
```
[...]

├── e8
├── e9
├── ea
├── eb
├── ec
│   └── eca42cd695ae8243fa0ab3d3e649bcdbcf603cc0572992c7df3615874ac91620
├── ed
├── ee
├── ef
├── f0
├── f1
├── f2
├── f3
├── f4
├── f5
├── f6
├── f7
├── f8
├── f9
├── fa
├── fb
├── fc
├── fd
├── fe
└── ff

257 directories, 5 files
```

**Comment by aawsome** [comment]
Thanks for opening the issue @AlphaJack.

Can you please be more specific what is your exact problem with having this 256 empty paths?

In fact, yes we could omit creating these folders and just create them on-demand. However, that would loose compatibility with restic which (IIRC) is not working when the paths are not present - as rustic is.

So, we can adapt rustic to be more resilient when those paths are note present (by creating them when they are needed), but if we initialize a new repo without creating these paths we get compatibility problems...

**Comment by AlphaJack** [comment]
Thank you for the clarification,
this is not a big issue on my side, more of a question.

I was asking because uploading ~255 empty folders with RClone seemed slow.
If I would tell RClone to ignore uploading empty folders from a repo, once I download my remote backup, I would end up having less folders than the original repo (because I would miss all non-empty folders).

But if Restic cannot handle missing folders, then I guess it's better to leave things as they are, to maintain compatibility.
As long as Rustic works correctly without empty folders, I can set the "don't upload empty folders" option from RClone.

**Comment by aawsome** [comment]
> As long as Rustic works correctly without empty folders

Actually I think it won't. But you can open issues for the errors you get when removing empty dirs - I'll fix them in the next release(s)...

**Comment by AlphaJack** [comment]
I'm getting this error with most operations (backup, prune, forget), but no further information about which file or directory is involved:


```
error: opening file failed: `Os { code: 2, kind: NotFound, message: "No such file or directory" }`
```

Can we also show the missing file or folder name in the error message?
