### ISSUE TITLE
docs: how to backup to B2

### ISSUE THREAD

**Issue by dsully** [rustic-rs/rustic#1319]
Hi - I'm currently using `restic` and wanted to try `rustic` as an alternative. However, I'm having trouble backing up directly to B2.

Here's the repository section of `rustic.toml`:

```toml
[repository]
repository = "rclone:b2:remote"
password-file = "..."
```

And my `rclone.conf`:

```
[remote]
type = b2
account = ...
key = ...
hard_delete = true
```

If I run `rustic backup`:

```
$ rustic backup
using config /root/.config/rustic/rustic.toml
[INFO] rclone output: 2023/04/28 16:54:26 Failed to create file system for "b2:remote": didn't find section in config file

Error: rclone exited with exit status: 1
```

I've tried various permutations of the repository name, with a `:` appended or removing `b2`:

```
$ rustic backup
using config /root/.config/rustic/rustic.toml
Error: No repository config file found. Is there a repo at rclone:remote:?
```

My existing `restic` config can backup directly to B2 without needing `rclone` at all.

The example here with OVH: https://github.com/rustic-rs/rustic/blob/main/examples/ovh-hot-cold.toml indicates I can do a direct backup to a remote provider.

Thanks

**Comment by simonsan** [comment]
The service config documentation is in the main repository under `/config/services`, here is an example using opendal for B2: https://github.com/rustic-rs/rustic/blob/main/config/services/b2.toml
