### ISSUE TITLE
`run-before` scripts will not run if the source paths are not present?

### ISSUE THREAD

**Issue by aur3l14no** [rustic-rs/rustic#1373]
If the sources are not present the `run-before` hook would not run at all. This kills use cases like using `run-before` hook to trigger fs snapshots creation.

https://github.com/rustic-rs/rustic/blob/852635e25c39b5ccd9f4c7b6bc544cc3f9a2f453/src/commands/backup.rs#L187

**Comment by aawsome** [comment]
Thanks for reporting @aur3l14no. I think #1374 will fix this.
