### ISSUE TITLE
Rustic can't find temporary logs directory, on Darwin/ARM64

### ISSUE THREAD

**Issue by vmlemon** [rustic-rs/rustic#1387]
After unpacking the Rustic 0.9.5 archive, on MacOS 14.3, I tried to create an archive, in an existing repository, only to receive the following error:
```
error: rustic-rs fatal error: path error: /log/rustic.log: No such file or directory (os error 2)
```
At least on MacOS, it should probably use /var/log, for this purpose. (Even with System Integrity Protection disabled, the root directory itself seems to be read-only, so a workaround, involving symlinking /var/log, to /log will also fail).

**Comment by aawsome** [comment]
@vmlemon Can you please give more details about what command you are using and the full output you are getting? Also a used config profile would be nice to see (of course you can remove sensitive information).

Rustic by default does not have any log directory, but writes logs to the path you specify for `log-file` (either in the config or via `--log-file`). So my guess is you set up that path there.

**Comment by vmlemon** [comment]
Thanks, I invoked it in the following manner:

```
root@Tysons-MacBook-Air Downloads # ./rustic -r /Volumes/SuperBox/Archive3 backup /Users
error: rustic-rs fatal error: path error: /log/rustic.log: No such file or directory (os error 2)
root@Tysons-MacBook-Air Downloads # 
```

That said, I don't use a configuration file, normally, so thanks for the tip - it looks like removing the sample files, that were in the release archive, at least made things work:

```
root@Tysons-MacBook-Air Downloads # ./rustic -r /Volumes/SuperBox/Archive3 backup /Users
[INFO] using no config file, none of these exist: /Users/tyson/Library/Application Support/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
enter repository password: [hidden]
[INFO] repository local:/Volumes/SuperBox/Archive3: password is correct.
[INFO] using cache at /Users/tyson/Library/Caches/rustic/f8b018aca0405d223d85cde74203c557de9b6febcf676f572e702214a5851e01
[00:00:09] reading index...               ██████████████████████████████████████[00:00:12] getting latest snapshot...     ████████████████████████████████████████       1154/1154      [INFO] using no parent
[INFO] starting to backup /Users ...
[00:02:42] backing up...                  ██████████████████░░░░░░░░░░░░░░░░░░░░░░ 106.69 GiB/230.32 GiB 733.79 MiB/s (ETA 3m)[WARN] ignoring error: Error: Failed to open ReadSourceOpen at `/Users/tyson/Library/Caches/com.apple.AppleMediaServices/Engagement/kvs-B.db`
Failed to open file at `/Users/tyson/Library/Caches/com.apple.AppleMediaServices/Engagement/kvs-B.db`. Please make sure the file exists and is accessible. (kind: related to input/output operations): caused by: Illegal byte sequence (os error 92)
[WARN] ignoring error: Error: Failed to open ReadSourceOpen at `/Users/tyson/Library/Caches/com.apple.AppleMediaServices/Engagement/kvs-B.db-shm`
Failed to open file at `/Users/tyson/Library/Caches/com.apple.AppleMediaServices/Engagement/kvs-B.db-shm`. Please make sure the file exists and is accessible. (kind: related to input/output operations): caused by: Illegal byte sequence (os error 92)
[WARN] ignoring error: Error: Failed to open ReadSourceOpen at `/Users/tyson/Library/Caches/com.apple.AppleMediaServices/Engagement/kvs-B.db-wal`
Failed to open file at `/Users/tyson/Library/Caches/com.apple.AppleMediaServices/Engagement/kvs-B.db-wal`. Please make sure the file exists and is accessible. (kind: related to input/output operations): caused by: Illegal byte sequence (os [00:04:43] backing up...                  █████████████████████████░░░░░░░░░░░░░░░ 148.82 GiB/230.32 GiB 429.97 MiB/s (ETA 3m)
```
In fairness, I didn't know what to expect, leaving the sample files in place, since I've usually always moved them into another directory, and fed that to Rustic, for testing.

**Comment by simonsan** [comment]
Ah, then it was due to having the example files polluting your environment. The `config` files that are packaged are really just to make it easier for you to setup `rustic` more easily. They won't work out of the box without you making changes to it. And I would say the preferred way to use `rustic` is actually by using profiles. So looking at them and adapting that workflow will be helpful. I'm closing this, as the problem seems to be accidental. If there are any other problems related to it, feel free to reopen. 🚀
