### ISSUE TITLE
overwork logging and log levels

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#209]
see #132 

Log levels shoudl be: tracing, debug, info, warning, error (use log crate)

Log output should be either stderr or file

**Comment by aawsome** [comment]
closed by #214

**Comment by ser** [comment]
it's impossible to guess it and log levels are not displayed with `--help` switch

**Comment by aawsome** [comment]
Thanks @ser for pointing to this! I think it should be in the docu. But we'll nevertheless need to add it to the CLI help text...

**Comment by aawsome** [comment]
The possible values are now in the CLI help, see #1663
