### ISSUE TITLE
Behavior when cache is missing

### ISSUE THREAD

**Issue by thht** [rustic-rs/rustic#221]
Hi,
I might have a quite peculiar use case... I need to run rustic on an ephemeral machine. This means, that there is not going to be a persistent cache. The backup source is also on a remote, mounted by `rclone`.

My question is: Does rustic in this case need to reread all the files? I.e. will this lead to a redownload of the whole source everytime I start the backup even if not much has changed?

From my first trials, it at least seems that rustic treats all files as "new", although it realizes that it these files (or their data more specifically) are already in the repo:

```
Files:       41 new, 0 changed, 0 unchanged
--
Dirs:        7 new, 0 changed, 0 unchanged
Added to the repo: 248 B (raw: 364 B)
processed 41 files, 180.2 MiB
```

**Comment by aawsome** [comment]
Thanks for your question!

Your behavior is not specific to caching. It's more about using a parent and if, whether the change detection works as expected.

Do you see a `using parent xxxx` message?
If yes, then this means the change detection doesn't work. This can happen for mounted remote file systems. You should try to use the `--ignore-inode` and/or the `--ignore-ctime` flags.
If no, then no parent is used. Do you always mount the source into the same mount point?

**Comment by thht** [comment]
this is my output:
```
backing up /mnt/nextcloud...
--
getting latest snapshot...
using no parent
determining size of backup source...
starting backup...
Files:       41 new, 0 changed, 0 unchanged
Dirs:        7 new, 0 changed, 0 unchanged
Added to the repo: 248 B (raw: 364 B)
processed 41 files, 180.2 MiB
snapshot dbc5d0da successfully saved.
backup of /mnt/nextcloud done.
```

and yes, the mount point is always the same...

**Comment by thht** [comment]
No idea if it is important, but this is a hot/cold repo config

**Comment by aawsome** [comment]
There is no parent used. If you don't specify a parent manually, the last snapshot with identical host/paths is used. Is your hostname or mountpoint changing during your backup runs?

**Comment by thht** [comment]
You mean the hostname on which everything runs? Yes, that changes. The mount point is constant.

Can I force rustic to ignore the hostname?

**Comment by thht** [comment]
ok. it was enough to call `hostname myconstant-hostname` to make it work. thanks for the hint!

**Comment by aawsome** [comment]
Yes, setting the hostname before calling rustic does the trick. I'll add the `--host` option (see #222) to allow users set the hostname for rustic when they cannot change the system hostname.

I'll close this issue. Feel free to reopen if you think anything is missing!
