### ISSUE TITLE
Prune error "Error: used pack 00b1373b does not exist!"

### ISSUE THREAD

**Issue by thht** [rustic-rs/rustic#249]
hi,
when i prune my repo after a successful backup, I get the following error:

```
Error: used pack 00b1373b does not exist!
```

What does this mean? Do I need to fix this? If yes, how do I fix this?

Thanks!"

**Comment by aawsome** [comment]
Seems you are missing this pack file. Can you run `rustic check` - it should give you the same error.

What version of rustic and which backend are you using? Before #230 (which is so far only included in the beta builds) it could happen that a upload via rclone or rest failed but the `backup` command doesn't retry or report an error. This bug fix needs to be released, but I was unfortunately a bit busy the last days...

**Comment by thht** [comment]
I am running the latest stable version 0.3.1 and use the rclone s3 backend.

but if i understand it correctly, as soon as you have published the new version, rustic should detect the missing pack file during a backup run and just create and reupload it. correct?

**Comment by aawsome** [comment]
Ok. Sorry that I didn't manage to release the bug fix earlier.
Unfortunately it will not suffice to just re-run the backup. So far this missing pack file is contained in the index and therefore the `backup` command will think the data is already there when you re-do a backup.

So, the index needs to be rebuilt - I planned to add a `--repair-index` option to the check command to do this. There are different cases how an index must be repaired where removing packs which are not present is the simplest one. So I'll just start with this "repair" option.

After the index is corrected, a consequent backup heals the repo - IF all data which is missing in the repository is still available in the backup source.

**Comment by thht** [comment]
no worries!

actually, the `check` command returns three packs that are in the index but not present.

is there a way to know which snapshots they belong to so i now what to `forget` and `prune`?

**Comment by aawsome** [comment]
> is there a way to know which snapshots they belong to so i now what to `forget` and `prune`?

No, unfortunately not. At this point the `check` command only checks the index independent of existing snapshots.

**Comment by thht** [comment]
would i be able to use restics `rebuild-index` to fix my repo?

**Comment by thht** [comment]
keeping in mind that it is a hot/cold storage style repo...

**Comment by aawsome** [comment]
In #255 I implemented a repair command which should help you to repair your repository.
With that PR you can run `rustic repair index` to remove the missing pack files from the index.

Then, another run of `rustic check` will show you which blobs are actually missing and which files these blobs belong to. Another backup of these files (if they didn't change meanwhile) will heal your repo.

**Comment by aawsome** [comment]
#255 has been merged. So, you can also run `rustic repair index` using the latest beta build.
