### ISSUE TITLE
backup/restore: Allow to handle absolute and relative paths

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#294]
(inspired by https://github.com/restic/restic/pull/3200)

Currently, rustic always converts the backup target into an absolute path. There is the `--as-path` (#280) option to change that path, but still all is done for absolute paths.

We could change the behavior to allow relative paths and distinguish between absolute and relative paths
- backup: if a relative path is given, save the exact relative path in the `paths` field of the snapshot and only save the relative path tree. Allow to use `--as-path` to convert absolute paths to relative ones and vice versa.
- restore: restore currently already works as if all paths are relative w.r.t. to the restore target. This could be enhanced for saved absolute paths: In this case, allow to omit the restore target and use the saved absolute path.

**Comment by damoclark** [comment]
[Relevant matching issue for Restic](https://github.com/restic/restic/issues/4026)
