### ISSUE TITLE
cannot use rustic with --password-command

### ISSUE THREAD

**Issue by tricarte** [rustic-rs/rustic#310]
Could you give an example on using `--password-command ` because what I tried does not work. I'm storing the password of the repository in a gpg encrypted file called `rustic-pass.gpg`. To output the content, I use: `gpg --no-tty -q -d rustic-pass.gpg`.

`rustic -P profile-name --password-command "gpg --no-tty -q -d rustic-pass.gpg" any-rustic-subcommand-here"`

This is the output:

```
using config /home/username/.config/rustic/profile-name.toml
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/backend/local.rs:27:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
And `RUST_BACKTRACE=full` does not return any useful information. 

Also using `password-command` setting in toml config or using `RUSTIC_PASSWORD_COMMAND` env variable all return the same error. Am I missing something or misunderstanding something?

Thanks in advance.

**Comment by aawsome** [comment]
@tricarte Did you close this issue because you already solved it?

For me this looks like you are having a permission problem to create the repo at the local dir you are using as repo-path. So, you should have a look at `--repository` (or the `RUSTIC_REPOSITORY` env variable or the `repository` entry in your config file).

**Comment by tricarte** [comment]
After ten minutes of struggling, I realized that I didn't mount the disk where the repository is in. Sorry for being silly.

**Comment by aawsome** [comment]
No need to be sorry! Actually the error message is not that clear here and should be at least changed to say permission of which file/dir is missing. That maybe would have helped you to not struggle for 10 minutes but maybe only for one ;-) 
So, sorry for the non-optimal error messages - this is still on my TODO list.
