### ISSUE TITLE
Error: output of 'rclone version' doesn't start with 'rclone v'

### ISSUE THREAD

**Issue by liblit** [rustic-rs/rustic#333]
Rustic 0.4.1 does not care for the version output of `rclone` on my Fedora 37 Linux machine:

```
% ./rustic --repository rclone:restic: snapshots
Error: output of 'rclone version' doesn't start with 'rclone v'
```

The actual output of `rclone version` is:

```
rclone 1.60.0
- os/version: fedora 37 (64 bit)
- os/kernel: 6.0.10-300.fc37.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: dynamic
```

**Comment by aawsome** [comment]
Thanks for reporting! Actually the version check is to warn if the rclone version is too low to support setting the connection password via env variable. I didn't expect there are rclones around which show other fornats for the version. I'll adapt this check.

In meanwhile you can use a vanilla rclone (download the binary) or manualky start rclone serve restic and connect via the rest backend.

**Comment by aawsome** [comment]
Can you try out #334? It should be able to handle the rclone output of the version you are using and in any case only print out a warning if the rclone version can not be determined.

**Comment by liblit** [comment]
#334 works perfectly for me. Thank you! :+1:

**Comment by aawsome** [comment]
@liblit Thanks for testing! The bug is now also fixed in the latest beta builds.
