### ISSUE TITLE
0.4.2 not available via crates.io

### ISSUE THREAD

**Issue by NobbZ** [rustic-rs/rustic#377]
0.4.2 is not listed on crates.io.

https://crates.io/crates/rustic-rs/versions

**Comment by aawsome** [comment]
Thanks for opening the issue. There is actually https://github.com/green-coder/cdc/pull/7 which prevented me from publishing to crates.io. I hope this gets fixed soon so I can upload soon a version to crates.io.

**Comment by aawsome** [comment]
The same problem exists for 0.4.3...
