### ISSUE TITLE
Unhelpful error message when password file was not found

### ISSUE THREAD

**Issue by NobbZ** [rustic-rs/rustic#378]
It is not clear what file was not found:

```
$ RUSTIC_PASSWORD_FILE=$(pwd)/does_not_exist rustic repoinfo -r rest:https://restic.mimas.internal.nobbz.dev/nobbz
Error: No such file or directory (os error 2)
```

When I set the equivalent through a profile (`-P`) it took me quite a while to figure out what exactly was missing, as there was a slight typo in the filename that I didn't spot at first.

**Comment by aawsome** [comment]
Thanks for opening the issue! You are right, this isn't helpful and I remember that I also once ran into this error and steuggled to find the cause. I'll improve the error message!
