### ISSUE TITLE
replace prettytable-rs?

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#42]
As prettytable-rs doesn't seem to be actively maintained, see https://github.com/phsym/prettytable-rs/issues/139

This is related to #30.

**Comment by JMarkin** [comment]
I think, good crates.
- [comfy-table](https://crates.io/crates/comfy-table)
- [tabled](https://crates.io/crates/tabled)

Checklist:
 - `should be free to use, of course (i.e. right licence)` all MIT
 - `being well maintained` < 1 month of last update
 - `having few other dependencies` from 2 to 3 required dependencies

I think comfy-table more similar to current code then tabled

What do you think about these crates ?

**Comment by aawsome** [comment]
@JMarkin  When I had a quick lock, I also found those. So, yes, they are both good candidates. If you are willing, choose the one you think fits better (or the one you like more) and propose a PR. Thank you very much in advance!

**Comment by aawsome** [comment]
closed by #290
