### ISSUE TITLE
Allow empty passwords

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#433]
This is, essentially, a duplicate of this issue from restic. I, and many others, would love to be able to create backups without needing a password. Could a flag be added for this? 

https://github.com/restic/restic/issues/1786

It is something that would be useful for many users, in particular for using rustic as an incremental backup mechanism in the open source Cyberpanel server control panel https://community.cyberpanel.net/t/cyberpanel-backups-v2-proposal/40370/

**Comment by aawsome** [comment]
You can already use an empty password with rustic. Typing just <Enter> for the password prompt works as well as setting `RUSTIC_PASSWORD=""` or specifying `password = ""` in the config file.
