### ISSUE TITLE
GLIBC 2.29

### ISSUE THREAD

**Issue by usmannasir** [rustic-rs/rustic#436]
Hello

We are trying to use latest rustic binary however it seems to require GLIBC 2.29 but almalinux have 2.28

```
NAME="AlmaLinux"
VERSION="8.7 (Stone Smilodon)"
```

If we install 2.29 it require to update/install many other stuff.

Which version of rustic binary is compatible with GLIBC 2.28

In reference to : https://community.cyberpanel.net/t/cyberpanel-backups-v2-proposal/40370

thanks

**Comment by aawsome** [comment]
The precompiled binaries are compiled using github latest ubuntu linux. If your glibc library version doesn't match, either

- compile rustic yourself, using `build.sh`  (after installing the rust toolchain, e.g. using https://rustup.rs/)
- Use the `musl` version of the binary which includes libc and is basically statically linked.

**Comment by usmannasir** [comment]
ok `musl` version works, thanks alot.
