### ISSUE TITLE
Recommendations for incremental backups of a mysql/mariadb database? 

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#451]
Do you have any suggestions on how to go about backing up a database in an incremental fashion? If anything has changed in it (quite likely), a full exported backup file would be recognized as different by rustic and the whole thing backed up.

MySQL and mariadb have incremental backup tools, but I'm not sure how to go about using it with rustic.

https://mariadb.com/kb/en/incremental-backup-and-restore-with-mariabackup/

**Comment by usmannasir** [comment]
I feel it will backup the complete dump

**Comment by aawsome** [comment]
About the incremental backups offered by some databases: They can be also used. But in this case I'd suggest to save the "base" and the "increment" on the disc and do a normal backup of the relevant dir. After the backup, you can remove the "increment" just to add a new "increment" based on the (unchanged) "base" before the next backup run.
But then you'd also have to decide at which point you would like to update the "base"...

IMO this is too much effort and you can go with the pipe solution in many cases without trouble.

**Comment by aawsome** [comment]
I'm closing this issue as the discussion has continued already here: https://community.cyberpanel.net/t/cyberpanel-backups-v2-proposal/40370/85
