### ISSUE TITLE
command to show snapshots by parent

### ISSUE THREAD

**Issue by usmannasir** [rustic-rs/rustic#452]
Hi,

let say i've created a snapshot using

```
rustic -r rclone:testremote:cyberpanel.net backup /home/backup/cyberpanel.net/config.json --password "" --parent fb6f173a58e2e5f3e4e55471989092234d3d042a9ea693f25f04301c59ffdb5b
```

Now how can I see childs of `fb6f173a58e2e5f3e4e55471989092234d3d042a9ea693f25f04301c59ffdb5b`

thanks.

**Comment by aawsome** [comment]
I'm still trying to figure out your use case where you need to find the parent.
It seems you want to have that `config.json` at hand when you restore the snapshot `fb6f173a58e2e5f3e4e55471989092234d3d042a9ea693f25f04301c59ffdb5b`, right?

I think a much better solution would be to simply backup that `config.json` together with all you've backuped into just one snapshot. #458 will allow you to do
`rustic backup <YOUR_SOURCE> /home/backup/cyberpanel.net/config.json`

You then can even independently restore both paths by:

```
rustic restore <SNAP>:<YOUR_SOURCE> <DESTINATION>
rustic restore <SNAP>:/home/backup/cyberpanel.net/config.json /path/to/restore/json/
```

Hope this is able to simplify your setting...

**Comment by usmannasir** [comment]
You understood the problem right, however, when I put two paths in backup command it create two seprate snapshots then I don't know the snapshot of the config one.

Actually each snapshot of database, data (files) need to have config of that specific time attached to it..

**Comment by aawsome** [comment]
> when I put two paths in backup command it create two seprate snapshots then I don't know the snapshot of the config one.

This is exactly what #458 changes. After this is merged, only 1 snapshot will be created.

**Comment by usmannasir** [comment]
wao, let me check

**Comment by aawsome** [comment]
Closing this as I think #458 covers the use case.
