### ISSUE TITLE
Split rustic into library and binary crate

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#461]

**Comment by Helithumper** [comment]
I'd also appreciate this split as it would allow other programs to natively add Restic support without needing to use separate `restic` processes.

The particular use cases I could think of are primarily around writing programs where you would want an integrated backup solution in which Restic/Rustic would be an appropriate and useful solution!

**Comment by aawsome** [comment]
@simonsan Thanks for your suggestion! I'll have a look at abscissa and see how much effort it would be. 

One thing is about to decide which kind of functionality to expose to a library interface. 
I think we should start with high-level functionalities (i.e. exactly the command which are available through the command line) which should be pretty easy to factor out. 

@simonsan If you are up to an PR, feel free to start. Would be nice if you already present it when its in an early stage, so we can discuss the general directions of this refactoring.
