### ISSUE TITLE
Restore into some specific path

### ISSUE THREAD

**Issue by usmannasir** [rustic-rs/rustic#463]
Hi,

When we do the restore using

```
sudo -u cyber5986 rustic -r rclone:testremote:cyberpanel.net restore a87e47e778cc6a46907924a2d4ee085e9287994c7e7e65613ca8647bc8253fd4 /home/cyberpanel.net/
```

It will also restore all the original folders inside `/home/cyberpanel.net/`, i mean the original folders where it was backed up from, if you just put `/` it will try to restore to the location it was backed up from which gives permissions error (expected).

But is it possible to just restore the actual final backed up folder to the given path?

thanks

**Comment by aawsome** [comment]
Try to use
```
rustic restore a87e47e778cc6a46907924a2d4ee085e9287994c7e7e65613ca8647bc8253fd4:/home/cyberpanel.net/ /home/cyberpanel.net/
```

**Comment by usmannasir** [comment]
```
[root@ip-172-31-15-45 test]#sudo -u cyber5986 rustic -r rclone:testremote:cyberpanel.net restore e8851436c7da7dcf91868fe7b9dc8674b14cde86c985f31c326fba2ef598eab9:/home/cyberpanel.net/ /home/cyberpanel.net/
using no config file (./rustic.toml doesn't exist)
enter repository password: 
[INFO] repository rclone:testremote:cyberpanel.net: password is correct.
[INFO] using cache at /home/cyberpanel.net/.cache/rustic/1ce86a489660a120b02aa40b7b9bb9b9704f2855d84e27289175e43a368f2d44
[00:00:00]                                ████████████████████████████████████████          0/0                      [INFO] getting snapshot...
[00:00:00] reading index...               ████████████████████████████████████████         13/13                     Error: "cyberpanel.net" not found
[root@ip-172-31-15-45 test]#
```
Please note backup of this file was not taken from `/home/cyberpanel.net`

**Comment by aawsome** [comment]
Sorry, then I didn't get how you made your snapshot. Can give me the full `backup`  command?

Also, please post the output of `rustic snapshots <ID>` and `rustic ls <ID>` (the ls shows the exact paths within the snapshots which you can use in the restore).

**Comment by usmannasir** [comment]
I think i got it, fixed by giving the path which was used in backup, thanks again

**Comment by usmannasir** [comment]
@aawsome how will you tackle https://github.com/rustic-rs/rustic/pull/458 if you have multiple sources?

I am talking in ref to this issue

**Comment by aawsome** [comment]
If you are wondering how to restore from a snapshot containing different sources: It doesn't matter at all for restore.
In fact you can restore any (sub-)tree and also any file within a snapshot - no matter how that tree or file is generated.

For example, if you have `/path/path1` and `/path/path2` in your snapshot, you can restore by `rustic restore <SNAP>:/path/path1 <DEST>`  and `rustic restore <SNAP>:/path/path2 <DEST>`  no matter if the snapshot was generated by `rustic backup /path` or by `rustic backup /path/path1 and /path/path2`.

**Comment by usmannasir** [comment]
Interesting, much thanks let me rewrite some code

**Comment by usmannasir** [comment]
It seems to be doing the job well, however, I hope you don't change this behaviour later because it will break lots of our code.

**Comment by aawsome** [comment]
> I hope you don't change this behaviour later because it will break lots of our code.

I do not have any plan to change this. Moreover, it is such an natural behavior plus the implementation is absolutely straight-forward, so I don't think this will be ever touched. 
Actually there is the need to add some blackbox tests in the CI/CD-pipeline to ensure this behavior, but this is basically all .

**Comment by usmannasir** [comment]
thank you, in regards to this, can you see my last comment here -> https://community.cyberpanel.net/t/cyberpanel-backups-v2-proposal/40370/90
