### ISSUE TITLE
unhelpful progress on "reading pack data" during "check"

### ISSUE THREAD

**Issue by liblit** [rustic-rs/rustic#467]
rustic v0.4.3 is operating on a local repository. `rustic check --read-data` is currently reporting that it is `reading pack data...`. The progress bar unhelpfully reports that it is done with `243/0` steps for this task, which gives me no information about how much work remains to be done.

Can `rustic` know how many steps there are in `reading pack data`, and can it use that to report more helpful progress through this `check` stage?

**Comment by aawsome** [comment]
Thanks for reporting!
I actually also noticed this and thought to maybe fix it in combination with #251. Adding this to a full check should be also not too hard...
