### ISSUE TITLE
`multibackup`: runs multiple backup runs in a row generating a couple of snapshots

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#472]
Add a command which runs multiple `backup` runs in a row generating a couple of snapshots.
Maybe add a `--merge` option once rustic-rs/rustic#411 is finished to directly merge them into one snapshot.

**Comment by dionorgua** [comment]
I'm not sure that I understand it correctly but it would be cool to have command that do a few backups one after another with completely different options (different tags, excludes, etc). 
Final result should looks exactly same as multiple independent `rustic` calls. The goal is to just save CPU time for loading indexes multiple times.

**Comment by aawsome** [comment]
@dionorgua Yes, this is exactly what the `multibackup` command would be meant for. Plus maybe an `--merge` option which does exactly the same as calling `rustic merge --delete` with all snapshots that has just been generated.

**Comment by aawsome** [comment]
Closing this, as it is already implemented using various `[[backup.snapshots]]` sections in the configuration profile.

**Comment by dionorgua** [comment]
@aawsome Is it documented somewhere? Sorry if it looks dumb. I was not able to follow this for a long time.
There are multiple places where I tried to look for, I think most verbose is README.md. But it still doesn't have anything about this.

**Comment by aawsome** [comment]
@dionorgua The example in https://github.com/rustic-rs/rustic/blob/main/config/rustic.toml creates two snapshots: one containing `/data/dir` and one containing `/home`
