### ISSUE TITLE
Elapsed time on `check` isn't updating

### ISSUE THREAD

**Issue by dimejo** [rustic-rs/rustic#5]
https://user-images.githubusercontent.com/25005220/172628002-e432fcdb-9c17-44cc-a857-4006152c91fd.mp4

**Comment by aawsome** [comment]
Thanks for reporting! In fact, rustic is using [the rc version of indicatif](https://docs.rs/indicatif/0.17.0-rc.11/indicatif/) which only updates anything when an increment happens.When checking all trees of a given snapshot, this can take quite some time until the snapshot is done and the increment is triggered.

Having a look at the indicatif docu, I realized there is an `enable_steady_tick` method which should solve this problem. I'll prepare a PR soon.

**Comment by aawsome** [comment]
@dimejo Can you check if #9 solves this problem?

**Comment by dimejo** [comment]
This fixes the issue. Thanks for the quick fix.

**Comment by aawsome** [comment]
I just merged #9. So the fix is now in master.
