### ISSUE TITLE
Is there a way to disable progress bar?

### ISSUE THREAD

**Issue by waspoza** [rustic-rs/rustic#515]
I have script that listens to directory changes and fires backup in case of a change. But after a backup output looks like this:
![Screenshot from 2023-03-22 18-25-10](https://user-images.githubusercontent.com/4631033/226989127-8bfa89de-bb34-44e9-b9b3-dd4ce9cbf43c.png)
Would be great if there was option to disable progress bar leaving only backup stats.

**Comment by aawsome** [comment]
Just wanted to note that the env variable `RUSTIC_PROGRESS_INTERVAL` is already supported.
But #525 will be merged soon which will support to disable progress bars totally.

**Comment by waspoza** [comment]
Thanks a lot!
