### ISSUE TITLE
Some commands timeout with rclone

### ISSUE THREAD

**Issue by parasiteoflife** [rustic-rs/rustic#523]
I'm trying to restore a snapshot from a restic repository using rclone but it always times out. I tried:

- Restoring from Windows. It times out.
- Restoring form Windows specifying the URL and port of the rclone serve. It times out.
- Restoring from Linux. It times out.
- Restoring from Linux specifying the URL and port of the rclone serve. It times out.

Listing the snapshots does work, the repository must have ~3000 snapshots if that has anything to do with that.

Trying to retrieve the repository info also timeout, this is the same error I always get, it's always with `/index/`:

```

[INFO] repository rclone:remote:restic: password is correct.
[INFO] using cache at /root/.cache/rustic/d90d022df2fb823131a02de585863aa60c12625ab6f20315326e657591feface
[INFO] scanning files...
[WARN] Error error sending request for url (http://127.0.0.1:46241/index/): operation timed out at 642.974464ms, retrying
[INFO] rclone output: 2023/03/23 12:49:26 ERROR : index: list failed: &fmt.wrapError{msg:"couldn't list directory: context canceled", err:(*errors.errorString)(0xc00011e0b0)} *fmt.wrapError

[WARN] Error error sending request for url (http://127.0.0.1:46241/index/): operation timed out at 587.699263ms, retrying
[INFO] rclone output: 2023/03/23 12:49:57 ERROR : index: list failed: &fmt.wrapError{msg:"couldn't list directory: context canceled", err:(*errors.errorString)(0xc00011e0b0)} *fmt.wrapError

[WARN] Error error sending request for url (http://127.0.0.1:46241/index/): operation timed out at 1.219423732s, retrying
[INFO] rclone output: 2023/03/23 12:50:27 ERROR : index: list failed: &fmt.wrapError{msg:"couldn't list directory: context canceled", err:(*errors.errorString)(0xc00011e0b0)} *fmt.wrapError

[WARN] Error error sending request for url (http://127.0.0.1:46241/index/): operation timed out at 1.979637741s, retrying
[INFO] rclone output: 2023/03/23 12:50:58 ERROR : index: list failed: &fmt.wrapError{msg:"couldn't list directory: context canceled", err:(*errors.errorString)(0xc00011e0b0)} *fmt.wrapError

[WARN] Error error sending request for url (http://127.0.0.1:46241/index/): operation timed out at 3.295870337s, retrying
[INFO] rclone output: 2023/03/23 12:51:30 ERROR : index: list failed: &fmt.wrapError{msg:"couldn't list directory: context canceled", err:(*errors.errorString)(0xc00011e0b0)} *fmt.wrapError
```

Sometimes I get this:

`[WARN] Error error sending request for url (http://localhost:4041/snapshots/): operation timed out at 547.183ms, retrying`

**Comment by aawsome** [comment]
This seems to be a problem of rclone. Can you access the index using rclone directly? What is the output of  `rclone ls <PATH>/index/`?

**Comment by aawsome** [comment]
Thanks for the explanation - this is actually a really slow storage backend...
The default timeout for http requests is 30s - this explains your behavior. The problem is that if the request timed out, rustic does retry - but if this also takes that long, the retry request also times out. And so on, until the maximum retries are reached...

I added the possibility to manually set the timeout in #524 (already contained in the latest beta build).
This is however currently only possible to set in the config file:
```
[repository]
repository = "rclone:..."
...

[repository.options]
timeout = "5min"
```

**Comment by aawsome** [comment]
Edit: Another solution would be that once rclone receives a part of the listed items, it should send them directly to rustic. That would prevent the connection "rustic -> rclone" from timing out in your case. But it seems that the rclone behavior is to first collect all items and then send them in one response.
