### ISSUE TITLE
`one-filesystem` not supported in configuration file

### ISSUE THREAD

**Issue by dimejo** [rustic-rs/rustic#547]
I just upgraded to rustic 0.5.0 and got an error on my first backup run:
`Error: unknown field 'one-filesystem'`

The configuration basically looks like this:
```
[global]
log-level = "info"

[repository]
repository = "/backup/rustic"
password-file =  "/home/user/.config/rustic/rustic.pass"
no-cache = true

[forget]
dry-run = true
keep-hourly = 24
keep-daily = 30
keep-weekly = 52
keep-monthly = 60

[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]
one-filesystem = true

[[backup.sources]]
source = "/path/to/backup"
tag = ["one"]
```

I was expecting the `one-filesystem` option to work because it is used in the [example configuration](https://github.com/rustic-rs/rustic/blob/4fad663abdc3310465c32d7649d2d96551c3fa6f/examples/local.toml#LL21-L21C22).

**Comment by aawsome** [comment]
Actually the option was always `one-file-system`. Before 0.5.0, `one-filesystem` was ignored, now it gives an error.
