### ISSUE TITLE
Backup dirs with spaces doesn't work

### ISSUE THREAD

**Issue by keppo070** [rustic-rs/rustic#558]
Rustic V0.5.0

I'm borg user for linux but they dont have a Windows client. So looking for a alternative for windows. Found Restic and Rustic. I did some initial testing. Visually I like rustic better

Restic is able to download the files from onedrive that are freed up and than backup. Rustic says it cant find the file.  Dont know if this falls under VSS support

**Comment by aawsome** [comment]
Thanks for reporting your issue!
Can you give the exact output of rustic? Thanks!

**Comment by keppo070** [comment]
```using no config file (.\rustic.toml doesn't exist)
[INFO] repository H:\Backup\Rustic\Rustic-python: password is correct.
[INFO] using cache at C:\Users\Patrick\AppData\Local\rustic\783bc69db8b6a88590f76db547b2e6736af91d8f0102056886b8916fc44e073a
Error: The system cannot find the file specified. (os error 2)

**Comment by aawsome** [comment]
This actually not about files to backup. AS long as there is no "starting to backup..." in the logs, rustic did not even start the backup. I need to improve the error messages but I think your error happens when the index is read. Can you run 'rustic check' on the repo and if this fails without good error messsge, 'restic check'? Thanks!

**Comment by waspoza** [comment]
It's most likely bc dir name has spaces in it. I have same problem. I looked at the code and i think i found the reason in file src/repofile/snapshotfile.rs:
```
impl PathList {
[...]  
    pub fn from_string(sources: &str, sanitize: bool) -> Result<Self> {
        Self::from_strings(sources.split_whitespace(), sanitize)
    }
```
Seems like backup paths are being split by whitespaces. I tried replacing spaces with \u0020 in config.toml, but it didn't worked, bc toml is parsed before spliting and spaces are back.

**Comment by keppo070** [comment]
yes it was the space in my folder. "C:\Users\Patrick\OneDrive\Pictures\Camera Roll\2019" is working.  Had to enter the quotes...

**Comment by waspoza** [comment]
Ye, from command line it may be working, but if backup path is entered into config file like this:
```
[[backup.sources]]
source = "/home/piotr/dir with spaces"
```
then it still bugs out:
```
$ ls /home/piotr/dir\ with\ spaces
drwxr-xr-x 1 piotr piotr   4 2023-03-31 19:10 .
drwx------ 1 piotr piotr 948 2023-04-02 13:14 ..
-rw-r--r-- 1 piotr piotr   0 2023-03-31 19:10 aa
$ ./rustic -P test backup
using config ./test.toml
[INFO] repository /home/piotr/rustic_test: password is correct.
[INFO] using cache at /home/piotr/.cache/rustic/bcbb400559f5e2d884f009f8f2be955e401245d14ac73bc8607b7bc0db3d4e79
[WARN] error sanitizing source="/home/piotr/dir with spaces" in config file: No such file or directory (os error 2)
```
I've tried single quotes, double quotes, replacing spaces with \u0020, nothing works.
