### ISSUE TITLE
Restoring symlinks fails setting owner/group, permissions and times

### ISSUE THREAD

**Issue by jvandenbroek** [rustic-rs/rustic#573]
When restoring symlinks, the following warning appears and does not set them:
```
[WARN] restore "etc/systemd/system/syslog.service": setting User/Group failed.
[WARN] restore "etc/systemd/system/syslog.service": chmod failed.
[WARN] restore "etc/systemd/system/syslog.service": setting file times failed.
```
Tested as root on btrfs and ext4.

**Comment by aawsome** [comment]
Thanks for reporting! I think the reason is that `restore` currently does try to follow symlink when setting user/group and times. Moreover, chmod on a symlink isn't allowed and therefore should not be tried by rustic.

**Comment by jvandenbroek** [comment]
Thanks again for your quick fix! There is just one warning left (not sure if that was there before tbh) when a symlink already exists:
`[WARN] restore "etc/systemd/system/syslog.service": creating special file failed.`

But it now does set the correct owner and times :+1:
