### ISSUE TITLE
backup from stdin: --stdin-filename is not used in path

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#575]
`> echo test | rustic backup --stdin-filename test -` gives:
```
> rustic snapshots 9e4
|----------|---------------------|----------|-------|------|-------|-------|------|------|
| 9e47fd89 | 2023-04-12 12:30:58 | latitude |       |      | test  |     1 |    1 |  5 B |
1 snapshot(s)
> rustic ls 9e4
"stdin" 
```

The filename in the tree should be `test` as well.

**Comment by usmannasir** [comment]
Looks like does not happen on alma linux but on ubuntu only?

**Comment by aawsome** [comment]
@usmannasir Seems this has been introduced by #425. That is, it did work in all pre-0.5.0 versions and just stopped working in 0.5.0. Maybe you snapshots on alma linux were created by a previous version? (You can check by running `rustic snapshots <ID> --long` or `rustic snapshots <ID> --json` and look for the `version` field.)

**Comment by usmannasir** [comment]
Is this beta on published to stable already?

**Comment by aawsome** [comment]
#576 has been merged into main; beta builds are currently run, I think they will be finished in a couple of minutes.
It will be part of the next release, which will be most likely 0.5.1.

**Comment by usmannasir** [comment]
ok, i will test it out and yes on my alma machine i might be having older version

**Comment by usmannasir** [comment]
Yes, it seems to be resolved, thanks alot
