### ISSUE TITLE
README must clearly reflect actual limitations comparing to Restic to avoid misunderstanding

### ISSUE THREAD

**Issue by zoulja** [rustic-rs/rustic#587]
Hi!
I looked at `can therefore be used as a complete replacement for restic.` and decided to give Rustic a try.
And immediately got **Error: backend s3 is not supported!** 😢
Let's face it - the above description is deliberately misleading, deliberately hides important details, and will only make users disappointed and unhappy, not attract them to this project as one might expect. `¯\_(ツ)_/¯`
Anyway Rustic looks very promising, I wish you all the best, hope someday we will meet again 🤗

**Comment by aawsome** [comment]
@zoulja Thanks for submitting this issue. 

S3 is actually supported using the `rclone` backend. For native support, see #546. 

I'm sorry if you got the feeling that the description is misleading - this is for sure note deliberately, maybe by accident or mistake. Feel free to open a PR to suggest a better README - Thanks in advance!

**Comment by zoulja** [comment]
Hi @aawsome, thanks for checking this!
Frankly speaking now I'm confused even more, since README doesn't contain any mention of `backend` 
Also I couldn't find any link to extended documentation, which could explain that ☹️

**Comment by aawsome** [comment]
@zoulja: To use S3 via the rclone backend, you have to setup rclone to be able to access your S3 storage, see https://rclone.org/s3/

Then, you can use rustic with `--repository rclone:<RCLONE_CONFIG_NAME>:path/to/repo`. This can also be set in the config file or using the env variable `RUSTIC_REPOSITORY`.

I know that documentation is an issue, see #302.
