### ISSUE TITLE
Report how much space would be saved if one or more snapshots were removed (pruned)

### ISSUE THREAD

**Issue by dlight** [rustic-rs/rustic#611]
One usability issue with deduplication and compression is that even if a snapshot contains, say, 1GB of files, it doesn't mean that if this snapshot didn't exist you would save 1GB of disk space. It might save nothing if those same files are included in other snapshots, and even if not, it might save way less than 1GB of space if the data compress well.

But what if rustic had a feature to report how much disk space would be saved if some set of snapshots were removed?

(That's a feature I sorely miss in any system with deduplication, like btrfs and xfs - rather than running `du -h` to show the size of a set of directories, I want to show much much removing those files will change what is reported by `df -h` - this means not counting extents with multiple reflinks, *unless* all of them are contained in the directories passed as parameters; and in the case of btrfs, taking compression into account)

Note that having this tool report on removal of multiple snapshots is essential, because the amount of space saved by removing snapshots A and B (in any order) can be greater (or equal) than the amount saved by removing only A plus the amount saved by removing only B, because there may be files that are included in both A and B and no other snapshot. So it's possible that removing A will save 1GB, removing B will save 1GB, and removing A then B (or B then A) will save 500GB.

**Comment by aawsome** [comment]
Did you try out `rustic forget --dry-run --prune <ID> <ID> ...` ?

**Comment by dlight** [comment]
... okay, I didn't, thanks! Glad to see this is already implemented!
