### ISSUE TITLE
How to change the compression level?

### ISSUE THREAD

**Issue by Deedasmi** [rustic-rs/rustic#641]
I see it has clap arguments, but I can't quite figure out where to apply them.

**Comment by aawsome** [comment]
Compression level is a repository option, i.e. it is saved in the repository config and needs to be set only once (or when you want to change it).

You can already set it when initializing a repository and change it using the command `rustic config --set-compression`.

NB: Questions about usage are better placed in the Discussions, I'm closing this as IMO it is not an issue.
