### ISSUE TITLE
Invalid profile, leads to misleading error

### ISSUE THREAD

**Issue by thePanz** [rustic-rs/rustic#645]
I am using a profile.toml file as (first lines removed):

```
[[backup.sources]]
source = "~/Works/"
tag = "works" ← this is the faulty line (line 13)
git-ignore = true
```

Running rustic I get the following error:
```
Error: error reading TOML from config file

Caused by:
    TOML parse error at line 12, column 1
       |
    12 | [[backup.sources]]
       | ^^^^^^^^^^^^^^^^^^
    invalid type: string "works", expected a sequence
```

**Comment by aawsome** [comment]
Well, your toml is indeed invalid. `tag` requires a list of tags, see https://github.com/rustic-rs/rustic/blob/main/examples/full.toml.
So, you should use 
```
tag = ["works"]
```
Closing this as the config file uses the same name as the CLI - which has the `--tag` option (where also multiple tags can be defined).

**Comment by thePanz** [comment]
I understand that the "tags" should be a list, would it be nice if the error message would point to the `tag = "work` line, instead of  `[[backup.sources]]`.

The text `[[backup.sources]]` is also marked as the "erroring" part, that is the reason I found it confusing

**Comment by aawsome** [comment]
Ah, I see. Thanks for your comment.
Actually this is the standard behavior of the `toml` crate - see https://github.com/toml-rs/toml.
Don't know if there is already an open issue. In any case, this can't/won't be fixed within rustic, sorry.
