### ISSUE TITLE
Crash during backup

### ISSUE THREAD

**Issue by LordFPL** [rustic-rs/rustic#650]
Hello,

Rustic is crash with the following output : 
```
thread '<unnamed>' panicked at 'no unicode', src/backend/ignore.rs:373:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'readahead worker thread panicked: panic indicator set', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pariter-0.5.1/src/readahead.rs:132:21
```
It's a 15TiB repository, and the crash is on 7,47 TiB.
There is no disk full, i have try to relocate cache, disable cache and now a backup is running with "RUST_BACKTRACE=1" (will certainly have an error tomorrow).

Is this problem known ?
Rustic is running with musl version v0.5.3 on a RedHat 8.6
Source repository is a NFS share in readonly, and destination is a GPFS filesystem with two distincts folder ("repository" and "repo-hot", as "repository" will be archived on LTO tapes)

Thx in advance :)

**Comment by aawsome** [comment]
Thank you for reporting! Actually this seems to be caused by a non-unicode link target, see #117. However, rustic shouldn't crash in this case but just skip that file. I'll take a look how to fix it. But this will need a bit of time. I'm currently out of town...

**Comment by aawsome** [comment]
@LordFPL The fix should be available in the beta builds within the next minutes.

**Comment by LordFPL** [comment]
Many thx :) I will try and say if it's ok.

**Comment by LordFPL** [comment]
Backup is not complete, but log show me the bad link with a warning :
` Lara_upscale -> 'Lara_seq'$'\302''_upscale'`
Very bad link.... will contact the user for that ;)

Thx again !
