### ISSUE TITLE
Support global configuration files in /etc/rustic/

### ISSUE THREAD

**Issue by pheki** [rustic-rs/rustic#652]
I think it would be great to have global config files in `/etc/rustic/` which could be used for backups by "system" users (which don't have a home directory) or configurations shared between users, so for example one user could create the backup and other users would still be able to access it.

The configuration files at `~/.config/` would have precedence over `/etc/`.

If you're interested, I'm willing to find some time and give this a try.

**Comment by aawsome** [comment]
I also like the idea. Especially with the possibility to use other config file, see `use-profile`, there is a good use case to have global config options and maybe per-user config options referring to to the global ones.

Some notes:
- We are currently about to refactor rustic, see #617. Maybe you should wait for this to finish or base on this PR.
- Currently https://docs.rs/directories/latest/directories/struct.ProjectDirs.html is used. Maybe you can find a better crate which supports user/global config dirs.
- Please have in mind that we should stay compatible with non-linux systems, i.e. MacOS and Windows.

**Comment by pheki** [comment]
> We are currently about to refactor rustic

Oh, good to know! Waiting is good to me

> - Please have in mind that we should stay compatible with non-linux systems, i.e. MacOS and Windows.

Hmmm totally forgot about Windows... Here are some options I've gathered:

Windows:
- `%ProgramData%\rustic\config` (resolves to `C:\ProgramData\rustic\config`)

MacOS:
- `/etc/rustic/`
- `/usr/local/etc/rustic` (for software installed using homebrew)
- `/Library/Application Support/com.rustic.rustic` (I don't know the actual values you're using here but you get the point)
- `/Users/Shared/*` (could use `.config` or `Library/ApplicationSupport`)

For MacOS I think `/etc/` and `/usr/local/etc` are the best option (we could just check both directories).

> Currently https://docs.rs/directories/latest/directories/struct.ProjectDirs.html is used. Maybe you can find a better crate which supports user/global config dirs.

Just opened a issue there: https://github.com/dirs-dev/directories-rs/issues/82

**Comment by aawsome** [comment]
Yes, would be great to have this implemented upstream. But I'm also fine with adding global config support to rustic until it's conveniently supported by a crate.

**Comment by aawsome** [comment]
FYI, #617 has just been merged.
