### ISSUE TITLE
"error trying to connect: invalid peer certificate: UnknownIssuer" when using rest-backend with local CA and TLS

### ISSUE THREAD

**Issue by eikef** [rustic-rs/rustic#679]
When using a custom CA and a TLS-enabled REST-server backend, rustic errors out with

```
[WARN] Error error sending request for url (https://xxxx:8000/config): error trying to connect: invalid peer certificate: UnknownIssuer at 674.181643ms, retrying
```

There appears to be no way to make rustic aware of the CA.
Other tools (`wget`, `curl`, etc.) work just fine -- the custom CA is present in the system's CA bundles. This is on Linux (Fedora in this case).

If I understand correctly (and that is a big if), https://docs.rs/reqwest/latest/reqwest/ as included via https://github.com/rustic-rs/rustic/blob/3c5543007c74b186efecabe21277e0e7ea76f72a/Cargo.toml#L197-L202 appears to default to "webpki roots" ("rustls-tls: Enables TLS functionality provided by rustls. Equivalent to rustls-tls-webpki-roots.")  `rustls-tls-native-roots` may be more appropriate, or a way to configure this behavior.

As it stands there appears to be no way to work around this issue in rustic.

**Comment by eikef** [comment]
That works TLS-wise, yes! :-)

(at least a `init` does what it is supposed to do, I am running into an entirely unrelated 
```
[WARN] Error error decoding response body: invalid type: null, expected a sequence at line 1 column 4 at 629.871045ms, retrying
```
loop now when trying to actually create a backup, but a quick check tells me that also happens when I remove the TLS part)

**Comment by aawsome** [comment]
Great to hear that TLS works! I'll close this issue.
For your other error I opened #681 and will make a PR to close that soon...
