### ISSUE TITLE
REST backend: error decoding response body: invalid type: null, expected a sequence

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic#681]
Seems like some REST-Servers return `null` instead of an empty sequence...

**Comment by aawsome** [comment]
@eikef Can you test if #682 solves the problem (compiled binaries are here: https://github.com/rustic-rs/rustic/actions/runs/5263055298?pr=682)

**Comment by aawsome** [comment]
There is also a workaround until #682 is landed: You could use https://github.com/rustic-rs/rust-server instead of rest-server. Rust-server should - IIRC - give an empty array for an empty directory, whereas rest-server seems to put `null` in the json instead...

**Comment by aawsome** [comment]
I also opened a bug in rest-server (https://github.com/restic/rest-server/issues/238) as the response of rest-server vialotes the specification given for the REST API.

Concluding: 
- rest-server responds with a `null` in this case - IMO this is a bug (but restic is able to handle this bug)
- rclone does correctly respond with `[]` in this case.
- rust-server does correctly respond with `[]` in this case.

I think that the restic/rest-server solution will be to change the API specification in which case #682 will allow rustic to work with the changed specification.

**Comment by eikef** [comment]
Yes, this fixes the problem and rustic runs through. Thank you!
