### ISSUE TITLE
Rename project? (There's oh so many pieces of software called `rustic`)

### ISSUE THREAD

**Issue by LeoniePhiline** [rustic-rs/rustic#688]
There's even a `restic` rust wrapper that is called `rustic-backup`. 

Given all the search results below, should this project and org be renamed?

![image](https://github.com/rustic-rs/rustic/assets/22329650/ced0a363-4b2e-49f5-919d-6d0f7322391d)

Just a thought. :)

**Comment by aawsome** [comment]
TL;DR: rustic will not be renamed.

Thanks for the proposal. This topic however has been already discussed quite a lot.

Yes, there are several projects which call themselves rustic. However there's not much about backup in this field except a tiny wrapper. I think this rustic backup tool has become very fast one of the most popular projects with this name. I won't ask other projects to change their names, but I hope I also get some understanding that I won't put effort and energy in renaming something - even more when I don't see a very valid reason doing so.

Closing this issue as wontfix.
