### ISSUE TITLE
Missing "--no-scan " option ?

### ISSUE THREAD

**Issue by LordFPL** [rustic-rs/rustic#689]
Is it planned to add the "--no-scan" option ?
I have a folder with many (many many... ;)) objects... causing a very (very very) long "determining size..."

Thx in advance, and many thx for the work

**Comment by aawsome** [comment]
Currently, there is no `no-scan` option, but if you use `no-progress`, the scanning is omitted. Would you wish to have an option which doesn't scan, but still displays some progress (of course missing something like ETA and percentage, so no real progress bar)?

**Comment by LordFPL** [comment]
Exactly, having speed, and maybe file/folder currently on (i look @ /proc/../fd actually ;)), is the only "need".
I will test with no-progress to see the gain.
