### ISSUE TITLE
thread 'main' panicked at 'packs_to_delete has no time', rustic-rs-0.5.4/src/commands/prune.rs:536:54

### ISSUE THREAD

**Issue by DianaNites** [rustic-rs/rustic#710]
The prune command on my repository has become broken, panicking with the title whenever its run.

`rustic prune -n`

This worked previously, and now fails no matter how its called, dry run or not

I can't provide a backtrace because the release binary doesnt seem to be compiled with any debug info, so its all unknown

`rustic check` reports no issues, and repair finds no issues. Further snapshots seem to complete without issue.

----
System Info:

`rustic 0.5.4`, Backblaze B2 / rclone backend

`6.3.9-arch1-1`

**Comment by aawsome** [comment]
Thanks for reporting - this shouldn't be the case.

A little background: rustic sets the `time` field when writing packs, but restic doesn't. This field is used to implement some rustic features like keeping packs always for a minimum time.

So I guess you are using `prune` on a repository created/modified by restic, right?

**Comment by aawsome** [comment]
Actually just realized that this is about `packs-to-delete`. This should be only written by rustic - so I actually don't know why a time is missing here... Anyway, we can treat this much nicer than panicking...

**Comment by aawsome** [comment]
In #711 I have enhanced `check` to find this kind of problem and report how to proceed.
Moreover, `prune` was changed to handle this case correctly, i.e. to simply keep the pack with a newly set `time` field.

**Comment by aawsome** [comment]
@DianaNites Can you test if #711 solves your problem? Binaries are available here: https://github.com/rustic-rs/rustic/actions/runs/5375013480?pr=711 (end of page).

Can you please:
- run `check` - this should display some errors now
- run `prune` - this should work but keep the packs without `time`
- run `check` again - errors should be now gone
- Another prune run after 23h or the given `--keep-delete` should not remove the packs

**Comment by aawsome** [comment]
Actually don't know what is going wrong about your cache..

About the `no time` errors/warnings from `check`/ `prune`: Did you run `prune` in dry-run mode?

**Comment by aawsome** [comment]
Ah, got it. The processing was fine, bit the index was still filtered out for processing altogether. This is changed ind #711 and now building; test binaries will be available soon.

**Comment by aawsome** [comment]
https://github.com/rustic-rs/rustic/actions/runs/5379624726?pr=711

**Comment by aawsome** [comment]
> So after running it, check no longer reports errors, prune runs still error about the cache, and i'm trying to get prune to delete all the data now and can't seem to get it to, what flags should i pass for that?

If check doesn't report the "no time" errors, then the prune run successfully repaired it. The packs are kept for as long as specified by `--keep-delete`, which defaults to 23h. If you can ensure that you run `prune` exclusively, i.e. no parallel backup runs, you can use `--instant-delete` which will simply remove all unneded packs.
