### ISSUE TITLE
Binaries for Arm CPUs

### ISSUE THREAD

**Issue by KamikazeePL** [rustic-rs/rustic#750]
Could compile binaries for ARM CPU specialy for Raspberry Pi?

**Comment by aawsome** [comment]
Can you test if this binary works for you:
https://github.com/rustic-rs/rustic/actions/runs/5566119595
(at the end of that page)

**Comment by aawsome** [comment]
Edit: I mean the binary of the `armv7-unknown-linux-gnueabihf` target:
https://github.com/rustic-rs/rustic/suites/14328617694/artifacts/806413722
(should work for raspberry pi starting from version 2)

**Comment by KamikazeePL** [comment]
> Edit: I mean the binary of the `armv7-unknown-linux-gnueabihf` target: https://github.com/rustic-rs/rustic/suites/14328617694/artifacts/806413722 (should work for raspberry pi starting from version 2)

It is working Thank You.

**Comment by KamikazeePL** [comment]
Could add this binary file to beta versions page so anybody could test it?

**Comment by aawsome** [comment]
It is already there in the beta folder. Just the link in the main page is missing...

**Comment by aawsome** [comment]
I also added the link on the main page.
