### ISSUE TITLE
Add `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by simonsan** [rustic-rs/rustic#755]
We should add a `CONTRIBUTING.md` containing a few guidelines and things people should know before contributing:

- Explaining issue labels WRT https://github.com/rust-lang/rust/labels?page=1&sort=name-asc and https://github.com/winnow-rs/winnow/labels
```
A - Area
C - Category
D - Diagnostic
E - Call for participation
F - Feature
I - Issue e.g. I-crash
M - Meta
O - Operating systems
P - priorities e.g. P-{low, medium, high, critical}
PG - Project Group
perf - Performance
S - Status e.g. S-{blocked, experimental, inactive}
T - Team relevancy
WG - Working group
```

- guideline should state clearly that code that is changed and PRed needs to be tested (so the old code needs to be covered, and the test needs to be passing for the new code as well)
  - test coverage currently is low but we need a higher test coverage to refactor stuff, so this guideline seems reasonable 
  - like this we raise continuously the test coverage and make sure we don't pull in logical bugs, while we can still accept PRs

- workflow for PRs
  - e.g. not force pushing, so we can keep review comments

- example `CONTRIBUTING.md`: https://github.com/SFTtech/openage/blob/master/doc/contributing.md

**Comment by aawsome** [comment]
I would add that we expect PRs to contain tests for the new code and that we welcome PRs which also increase the general test coverage. Maybe add that PRs with test have a much higher probability of getting merged (fast).
