### ISSUE TITLE
Fully document environment variables

### ISSUE THREAD

**Issue by simonsan** [rustic-rs/rustic#768]
`rustic` reads various environment variables at runtime, that also interfere with configuration settings.

For a better overview, we should therefore document:
- [x] which environment variables there are
- [x] what is the priority these values are applied (`cli > env > config`?)

**Comment by aawsome** [comment]
> what is the priority these values are applied (`cli > env > config`?)

Exactly like this! But with restrictions: You can overwrite values, but for many,you cannot "unset" them.
