### ISSUE TITLE
Backup source with spaces does not work at all, thinks path does not exist

### ISSUE THREAD

**Issue by DianaNites** [rustic-rs/rustic#813]
full reproduction

```shell
$ mkdir -p /tmp/rustic/backup
$ mkdir -p "/tmp/rustic/has a space or four/"
$ rustic -P (realpath local) init
$ rustic -P (realpath local) backup

[INFO] repository local:/tmp/rustic/backup: password is correct.
[INFO] using no cache
[WARN] error sanitizing source="/tmp/rustic/has a space or four/" in config file: No such file or directory (os error 2)
[INFO] using all backup sources from config file.
[00:00:00] reading index...               ████████████████████████████████████████          0/0
```

With the following config in a file called `local.toml`

(rustic will unconditionally add .toml to any passed profile, but otherwise works with arbitrary paths)

```toml
[repository]
repository = "/tmp/rustic/backup"
no-cache = true # no cache needed for local repository

[backup]
one-file-system = true

[[backup.sources]]
source = "/tmp/rustic/has a space or four/"
```

**Comment by aawsome** [comment]
@DianaNites Thanks for opening the issue and for your suggestions! I agree that at least this has to be documented much better. 

The reason for the current behavior is - as always - historical reasons ;-)  Maybe I didn't think enough about a good solution when I added the multi-path option for backup...

Highly appreciate your suggestion! I hope we can work on it to improve rustic!
