### ISSUE TITLE
Use a different file name other than `.gitignore` for file-based ignoring

### ISSUE THREAD

**Issue by ProspectPyxis** [rustic-rs/rustic#832]
Currently, ignoring files via a `.gitignore` file is implemented. However, I'd like to use a different filename for the same purpose - something like `.rusticignore` to specifically exclude files for backing up but still allowing it in git repos, or vice versa.

This would also be useful for non-git directories.

I'd be willing to try and make a PR for this.

**Comment by aawsome** [comment]
@ProspectPyxis I support your enhancement wish - if you like to implement this feature, please go ahead! 

Some comments:

Note that currently the `ignore` crate which should support custom ignore files (at least some other commands using it support it, e.g. ripgrep). But we may change using `ignore` as file lister as there are quite some ignore-related open issues which would need a bit of rework.

Also note that currently we are changing rustic from a single-CLI-project into a multi-crate-project with `rustic_core` being the core library to support all functionality. So I think you have to implement functionality in `crates/rustic_core/src/backend/ignore.rs` and have to take care it also work within the rustic CLI. There are also some refactoring PRs open (e.g. #787) which will be merged with high priority, so prepare to rebase (or wait until the refactor is finished and 0.6.0 is released.. :wink: )

**Comment by ProspectPyxis** [comment]
Seems 0.6 is here now and the core code has been split to [rustic-rs/rustic_core](https://github.com/rustic-rs/rustic_core) - if I wish to make a PR for this now, I'd need to use that repository, correct?

Also, what are some issues that we currently have around the `ignore` crate? Not exactly relevant to the issue, but if the crate may be replaced in the future, I'd like to know the problems/potential solutions going on.

**Comment by aawsome** [comment]
Yes, this is a rustic_core topic now.

About the excludes rules: There are many open issues (about 5) regarding wishes that people have for different exclude behavior of rustic - including this issue.

Currently, rustic uses the `ignore` crate to get a list of local files (using `ignore`'s exclude options etc..) which it then backups. The `ignore` crate is not able to fulfill all open issues. So, I was already thinking about implemting rustics own excluding logic (which could use or mimic the `ignore` crate) and apply it to something like `walkdir` directly for a local backup source. Then users' wishes can be added in future to this logic. Moreover, another advantage is that this then could be easily used for other sources than local dirs which is also on my features list.
