### ISSUE TITLE
crates.io broken links

### ISSUE THREAD

**Issue by brahimABD98** [rustic-rs/rustic#872]
upon checking the crates.io [page](https://crates.io/crates/rustic-rs) multiple links seems to be no longer working such as
- [FAQ](https://github.com/rustic-rs/rustic/blob/HEAD/FAQ.md)
- [example config files](https://github.com/rustic-rs/rustic/blob/HEAD/examples/).
- [Comparison between rustic and restic](https://github.com/rustic-rs/rustic/blob/HEAD/doc/comparison-restic.md)

**Comment by aawsome** [comment]
Thanks a lot @brahimABD98 for reporting.
This is due to the refactoring of rustic into rustic_core and separate documenttion.
We need to soon prepare a new release...

**Comment by brahimABD98** [comment]
same for [docs.rs](https://docs.rs/crate/rustic-rs/latest) page these links are broken too
- FAQ
- examples

**Comment by aawsome** [comment]
Fixed by releasing 0.6.0
