### ISSUE TITLE
Per source hooks in the config file

### ISSUE THREAD

**Issue by rehanone** [rustic-rs/rustic#902]
Thanks a lot for creating wonderful alternative to the amazing `restic` program. I have been watching the progress of your project for a while and waiting for the right moment to jump on. We a few things have happened that cause me to seriously take a look at this project. I have been looking to restore a very old snapshot in restic and found the lack of any description very challenging in figuring out the right snapshot to pick. So the fact that this one has that ability is great incentive going forward. However I am using a wrapper for restic called autorestic which has the ability to call scripts/programs per source/location as hooks. I use this ability extensively to gracefully bring down containers before backup and bring them back up after the backup is complete. There is a documentation available for this feature [here](https://autorestic.vercel.app/location/hooks). There are 4 hooks supported:
- before
- after
- failure
- success

These hooks are per source. But I think there might be some value in having hooks that are called per repo as well.

**Comment by aawsome** [comment]
Thanks a lot @rehanone for your feature request!

I think this is quite a small enhancement which would only affect the rustic CLI and not rustic_core.

There are already several command which are called, see e.g. this [config file](https://github.com/rustic-rs/rustic/blob/main/config/full.toml) - and the called hooks could just add to this list.

**Comment by rehanone** [comment]
@aawsome , thanks for a very quick response. Yes I agree that is a very small change in the CLI only. It is already implemented on the repository level in `post-create-command` and `post-create-command` as you comment perhaps is alluding to.

**Comment by rehanone** [comment]
@aawsome, I would also like to suggest that making each of these hooks to be a list of commands rather than a single command would be much better in terms of making it flexible. This would not be a big change in the design but allows for adding arbitrary number of commands to be executed against each hook.

**Comment by zxcat** [comment]
+1. I am using restic+resticprofile wrapper and now trying to move to rustic.
There are `run-before`, `run-after`, `run-after-fail` and `run-finally` options in resticprofile, which I use from the 1st day. Each option can be a list of commands and also supports inheritance + env vars. E.g. you can define them on root level using env vars like `run-before: 'echo "== run-before profile $PROFILE_NAME and command $PROFILE_COMMAND"'` and then reuse on profile level or command level without any additional configuration.
For backup command I use something like
```yaml
  run-finally:
    - 'grep -Ev "(^unchanged\\s|\(0 B added, 0 B stored\))" {{$logName}} > "…/logs/bkp-$PROFILE_NAME/$(date '+%Y-%m-%d_%H-%M-%S').log"'`
    - # notify command here
```
To filter and organize logs and notify if something important happened.

Note: `$logName` here is a go template variable, but that's a different story. To make hook commands flexible it's enough to set some env vars, containing flags passed to rustic and calculated from current config. Actually, I only used `$PROFILE_NAME` and paths (source/repo/log-path).

Note 2: resticprofile runs each command in a list separately, so
```yaml
  run-after:
    - 'my_var=123'
    - 'echo $my_var'
```
outputs nothing. It may create some inconveniences, but seems more secure.


---
For reference: [resticprofile hooks](https://creativeprojects.github.io/resticprofile/configuration/run_hooks/index.html)

**Comment by rdelaage** [comment]
Hello I would also be very interested in for that feature. I also suggested hooks for other actions in autorestic (https://github.com/cupcakearmy/autorestic/pull/213) such as backup restore or checking for example.

**Comment by aawsome** [comment]
We have a WIP-PR for this: #1218 
Feel free to add any input to the discussion there - or try it out!
