### ISSUE TITLE
`rustic init --dry-run` creates repo

### ISSUE THREAD

**Issue by zxcat** [rustic-rs/rustic#905]
But help says:
```
--dry-run  -- Only show what would be done without modifying anything. Does not affect read-only commands
```

Seems it ignores `--dry-run`.

_(`rustic --version` =  `0.6.0`, built locally from 54c608c)_

**Comment by aawsome** [comment]
Thanks @zxcat for reporting.
The `dry-run` option was actually never implemented for the `init` command...
