### ISSUE TITLE
Doc Question: is 'forget --prune' the same as 'forget` with '[forget] prune = true' set in the configuration?

### ISSUE THREAD

**Issue by Schweber** [rustic-rs/rustic#914]
I'm sorry if this is descibed somewhere but if set

```
[forget]
prune = true
```
in my config, is running 'forget' with this config then the same as running 'forget --prune'?

The [example configuration](https://github.com/rustic-rs/rustic/blob/main/config/full.toml) has this setting but it is not explained (at least it isn't clear to me).

**Comment by aawsome** [comment]
Yes. The config file just pre-sets that option.

**Comment by Schweber** [comment]
Thanks!
