### ISSUE TITLE
Delete local files that are not in the snapshot

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#92]
Is it possible for rustic to delete local files that are not in teh snapshot? 

The use case is that you want to restore a folder to a specific point in time, removing any changes that might have been made after that point in time. It seems to me that this is a crucial feature in order for any backup tool, and is the default behaviour in most tools that I am familiar with but it is missing in restic (see this issue https://github.com/restic/restic/issues/2348)

**Comment by aawsome** [comment]
This feature is planned (see the `restore --delete` option which however is not working yet).

However, IMO there is another issue: when you backup, for instance `/path1/path2`, then restic saves a tree starting with `/`:
```
/
/path1
/path1/path2
/path1/path2/file
...
```
If you restore restore this to the destination path `/` and add the `--delete` option, every dir which is not `/path1` under `/` will be deleted. This is most likely not wanted. 
I need to  think about a good way to solve this...

**Comment by aawsome** [comment]
I think #93 solves the additional issue I've mentioned above. After that, I'll figure out how to implement the `--delete` option.

**Comment by aawsome** [comment]
@nickchomey PR #104 should already work for your use case. Can you test it?
(See the TODO for some missing edge cases, I'll add treatment for those soon)

**Comment by aawsome** [comment]
Ah, ok, you have to build it from source:
- install Rust
- check out the tree from https://github.com/rustic-rs/rustic/tree/restore-delete : 
   - `git clone https://github.com/rustic-rs/rustic.git`
   - `git checkout restore-delete`
   - Alternatively, download https://github.com/rustic-rs/rustic/archive/refs/heads/restore-delete.zip
- build the binary: `cargo build --release`

Tell me if I should provide a binary for you!
I might also review the code and merge it, then it's available as beta build...

**Comment by aawsome** [comment]
The `--delete` option is now merged and available via the beta builds:
https://github.com/rustic-rs/rustic-beta

You simply need to download and unpack (I use `tar xvfz <FILE>`) it.

**Comment by aawsome** [comment]
I'm closing this issue. Feel free to re-open or open a new issue if there are problems or wishes related to this functionality.
