### ISSUE TITLE
--time backup argument missing

### ISSUE THREAD

**Issue by florensie** [rustic-rs/rustic#924]
Restic allows manually setting the creation time of a snapshot when using the backup command with `--time`. Rustic appears to be missing this feature (although it's included in rustic_core).

**Comment by aawsome** [comment]
`--time` has been added to the backup command in 0.6.0. We currently have no builds, but you can get the latest version here: https://github.com/rustic-rs/nightly

**Comment by florensie** [comment]
Thanks, I missed that.
