### ISSUE TITLE
Rustic returns exit code 0 when errors occur

### ISSUE THREAD

**Issue by florensie** [rustic-rs/rustic#927]
For automation tools it would be useful if a non-zero exit code is returned when the repository is not initialized. In fact this is exactly what Restic suggests you do in their [scripting documentation](https://restic.readthedocs.io/en/stable/075_scripting.html#check-if-a-repository-is-already-initialized), but it doesn't work for Rustic:

```
/app # restic -r test cat config
Fatal: unable to open config file: stat test/config: no such file or directory
Is there a repository at the following location?
test
/app # echo $?
1
/app # rustic -r test cat config
using no config file, none of these exist: /root/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
error: No repository config file found. Is there a repo at local:test?
/app # echo $?
0
```

There may be more instances where exit codes are not properly implemented, but this is all I have tested as of now.

**Comment by aawsome** [comment]
@florensie Thanks for opening the issue - in fact rustic doesn't return exit codes if something fails. This should be enhanced.
A workaround is to grep the output for error messages or warnings in your scripts.

About the exit code when the repository is not initialized: What is your specific use case? If it is to check whether a repository should be initialized before backing up, try `rustic backup --init`.

**Comment by florensie** [comment]
For my case I need to check the existing snapshots before I do any backups, so unfortunately `--init` isn't an option. You could consider making `--init` a global parameter.

**Comment by aawsome** [comment]
Sorry for the late follow-up! Out of curiosity: Can you describe your use case in more detail? What do you want to do and where do you need the information if the repository is initialized?

**Comment by aawsome** [comment]
I just recalled that non-0 exit codes should be already implemented; at least I thought that 
```Rust
 if let Err(err) = self.inner_run() {
            status_err!("{}", err);
            RUSTIC_APP.shutdown(Shutdown::Crash);
        };
```
should do exactly this. But it seems it doesn't....
@simonsan Can you have a look at it?

**Comment by simonsan** [comment]
The corresponding PR with delivering an extra method for this has been merged and a new abscissa release will be made soon™️.

**Comment by aawsome** [comment]
@Schweber This is possible - but when uploading a version to crates.io, git dependencies are not allowed, only dependencies to projects/versions also released to crates.io...
