### ISSUE TITLE
Too much output during normal operation

### ISSUE THREAD

**Issue by troelsarvin** [rustic-rs/rustic#959]
When running rustic in a batch job, you want to have rustic be silent, unless something bad happens.

But when I run rustic like this:
  rustic --no-progress --log-level warn backup
rustic outputs "using config /etc/rustic/rustic.toml" on stderr.
And on stdout, it prints:
Files:       0 new, 1 changed, 2738 unchanged
Dirs:        0 new, 13 changed, 834 unchanged
Added to the repo: 13.4 kiB (raw: 66.6 kiB)
processed 2739 files, 92.6 MiB
snapshot 8ccb94a0 successfully saved.

The message on stderr is not an error message, so I claim it should be sent to stdout, if at all.
And I claim that with a "warn" log level, it should not write statistics etc.

**Comment by teon** [comment]
@aawsome I would like to "upvote" @troelsarvin comments and maybe begin a discussion that:
1. Typical unix approach is: be silent until something important is worth mentioning (or the --verbose is explicitly added)
2. A lot of log messages are in my opinion DEBUG messages that for a normal user **have no value**, example:
`[INFO] read_task; read_end_buffer_size=1024` - what this message brings of value when using to a user?
3. And even despite all the above a typical (what I'm used to) practice of INFO messages are "business messages" that inform about events and states that happened and are relevant to the user - a lot of messages are not that type...

Just my 2cents.

Ps. Love your guys work! thank you for an awesome tool!

**Comment by aawsome** [comment]
@teon You can easily use something like
```
log-level = "warn"
```
in your config profile. Also the option `--quiet` is already implemented.

Or did you want to start a discussion about what are good default values?

About that specific `[INFO] read_task; read_end_buffer_size=1024` - this is a info log which comes out of opendal, IIRC. I agree that this seems to be "wrong" severity from a rustic's user perspective, but this can be only changed within opendal (or its dependencies)
