### ISSUE TITLE
Improve activity report on `copy`

### ISSUE THREAD

**Issue by NobbZ** [rustic-rs/rustic#960]
Currently when one runs `rustic copy` there will be some output of rustic regarding reading the index, and also a list of relevant snapshots gets printed.

Once the actual copy gets started, `rustic` seems stale. There is no way to check whether it was actually doing things or not.

I can totally see that it is hard to give a proper estimate of how much data will have to be transfered overall, as snapshots might overlap/share blobs due to deduplication, and it is also not easily known which blobs will already be on the remote.

Still, I'd wish there was some sign of activity.

Perhaps print some self updating activity report, that includes the current snapshot being copied, from which repo it is copied, to which repo it is copied, what the current speed rate is and how much data has been transfered until now.

As amount of blobs to transfer and as such amount of data to transfer per snapshot can vary significantly, I am not sure if "copied $x of $y snapshots" would be a sensible or useful information either.

**Comment by aawsome** [comment]
I just realized that this information is already available, but not shown due to wrong initialization of the target repositories.
I'll make a fix PR!

**Comment by aawsome** [comment]
Update: The information available is something like snapshot x/total is copied..
This is better than nothing, but could be still improved...

**Comment by aawsome** [comment]
https://github.com/rustic-rs/rustic_core/pull/94 will add progress of already copied bytes and also the current (smoothed) transfer rate.
