### ISSUE TITLE
error: repo-hot is not a hot repository! Aborting.

### ISSUE THREAD

**Issue by mueckinger** [rustic-rs/rustic#978]
Hi,

I tried using the hot/cold pattern with scaleway. For scaleway you cannot predefine the storage class for a bucket, so you have to set it in your rclone config as follows:
```
[scaleway-cold]
type = s3
provider = Scaleway
env_auth = false
endpoint = s3.fr-par.scw.cloud
access_key_id = ***
secret_access_key = ***
region = fr-par
location_constraint =
acl = private
server_side_encryption =
storage_class = GLACIER

[scaleway-hot]
type = s3
provider = Scaleway
env_auth = false
endpoint = s3.fr-par.scw.cloud
access_key_id = ***
secret_access_key = ***
region = fr-par
location_constraint =
acl = private
server_side_encryption =
storage_class = ONEZONE_IA
```

When running init with rustic v0.6.1 it throws **error: repo-hot is not a hot repository! Aborting.**

```
$ rustic -r rclone:scaleway-cold:ca86aad8-771c-43ec-9787-894b03b16c63 --repo-hot rclone:scaleway-hot:ee03f556-8a01-455d-abe5-efaba76ad77b init
using no config file, none of these exist: /home/michael/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
enter password for new key: [hidden]
[INFO] key 5eda87b5 successfully added.
[INFO] repository f2d8c604 successfully created.
error: repo-hot is not a hot repository! Aborting.
```

Despite the error message both repositories appear to have been initialized correctly and can be used with `rustic backup`.

**Comment by aawsome** [comment]
Could it be that at `rclone:scaleway-hot:ee03f556-8a01-455d-abe5-efaba76ad77b` there is already a repository? `init` will initialize both the hot and the cold part.

**Comment by mueckinger** [comment]
No, only the buckets were created in advance.
I've just tried it again, with even non-existing buckets, but the output is the same:

```
$ rustic -r rclone:scaleway-cold:6b80f7ec-6dbb-4648-943a-729885a1367d --repo-hot rclone:scaleway-hot:7c512630-d05a-4dd7-9a0d-6fcc21b1a4e2 init
using no config file, none of these exist: /home/michael/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
enter password for new key: [hidden]
[INFO] key fb8a95ac successfully added.
[INFO] repository 9cd1ec55 successfully created.
error: repo-hot is not a hot repository! Aborting.
```

**Comment by aawsome** [comment]
Seem like this ist a wrong Error message introduced by the refactoring into rustic_core. Can you Check If the comnand `backup --init` ist also affected?

**Comment by mueckinger** [comment]
> Seem like this is a wrong error message introduced by the refactoring into rustic_core. Can you check if the command `backup --init` is also affected?

Happy new year! Appreciate your engangement. I can confirm that `backup --init` is also affected.

**Comment by aawsome** [comment]
@simonsan For the design of the rustic_core API and to introduce the `backup --init` command, I decided to return an `Repository<impl Open>` from the `init...()` commands which means they call `open_raw`. 
I think I missed some case for hot/cold reposiories there. I'll look into it and make a fix.

This repository-opening after initialization is actually not needed for for the plain `rustic init` command. So, here the repository is completely initialized before the error is wrongly returned. `rustic backup --init` is however currently broken for hot/cold repositories. I think the same applies to `rustic copy --init`.
