### ISSUE TITLE
Can't `diff` with a path begin with drive letter under windows

### ISSUE THREAD

**Issue by 9-2-1** [rustic-rs/rustic#998]
For example, `rustic diff f0ca1025:D:\data D:\data` will fail with error `error: no suitable id found for D`

Suggestion: treat single letter "id" as drive letter, or add an special "local" id to represent local path `local:D:\data`

**Comment by aawsome** [comment]
Thanks @9-2-1 for reporting. This is obviously a syntax problem here.
I opt for adding a `local:` prefix - as we might want to add remote source in future where we also might want to use `local:` as local fs.

**Comment by 9-2-1** [comment]
I realized that, under windows, backslash `\` is used in local path, while rustic only treat a string including `/` as a path, so paths like `D:\abc\`, `docs` and `folder\docs` won't work.

**Comment by aawsome** [comment]
With #1000, `local:D:\abc\`, `local:docs` and `local:folder\docs` should work.
It will be available in the next nightly builds, too (I guess tomorrow).
